### ISSUE TITLE
Colorise F# function arguments into color differenet that its name color

### ISSUE THREAD

**Issue by xperiandri** [tomasr/viasfora#108]
It is very hard to read F# function definitions especially if you only begin to use it.
Could you add ability to set a different color for function arguments than function name? So they can be visually split from function name.

It would also be useful in lambdas, maybe even in C#.

**Comment by tomasr** [comment]
Could you post an example of what you mean to clarify what you'd envision this to look like? I'm afraid I only know enough F# to be dangerous :)

**Comment by xperiandri** [comment]
<img width="872" alt="f colorisation" src="https://cloud.githubusercontent.com/assets/2365592/8722267/592e0360-2bcb-11e5-98fd-73559a1dda3a.png">
I will try to explain:
#### Problem
It is hard to distinct function name from function parameters.
#### What is on screenshot
```let``` is a binding (looks like declaring a variable for value or for lambda in C#).
After ```let``` a function name goes (or value name, in our case we are about functions).
After function name function parameters go. They can be either without type specification (inferred type) or with that ```(parameter : ParameterType)```.
Then returning value type can be specified ```: ReturningType```. Otherwise it is inferred from the last statement of function body.
Then ```=``` means that function signature is defined and after it function body goes.

To invoke a function you specify its name followed by parameters spitted by spaces or by comas (depending on signature).
Coma means that you have to pass all the parameters separated by comas because they will be combined into a ```Tuple<>```.
Space means that you can pass not all parameters but preserving order. In that case you will have returned not a value but another function that require other not specified parameters.
#### Conclusion
I want function name or function parameter to be highlighted (by foreground or background) so I can visually distinct them while reading a code.

**Comment by tomasr** [comment]
This is a great suggestion, but not sure how to implement it at the moment. It would require full parsing of F# code, which I don't do at the moment. A better option would be, imho, to add this as part of the F# VS integration directly: https://github.com/Microsoft/visualfsharp/

**Comment by xperiandri** [comment]
Agree
