### ISSUE TITLE
Editor Margin has fixed height and cuts text

### ISSUE THREAD

**Issue by xperiandri** [tomasr/viasfora#110]
If environment font is increased (in my case 12)

<img width="640" alt="environment font" src="https://cloud.githubusercontent.com/assets/2365592/8932445/e6573a9e-3545-11e5-97d5-fe151b2e8c6c.png">

Then Editor Margin still remains of the same height and cuts a bottom of text.

<img width="744" alt="editor margin cuts text" src="https://cloud.githubusercontent.com/assets/2365592/8932473/13d67728-3546-11e5-99f5-c96435d469d8.png">

**Comment by xperiandri** [comment]
Is it displayed by Viasfora? Or I mixed up?
Can't find a UI of this.

**Comment by tomasr** [comment]
Thanks for the report! Yes, this is part of Viasfora (controlled by the Enable Developer Toolbar setting or closing it with the X button at the right). I'll get this one fixed.

**Comment by xperiandri** [comment]
Do you have a build to try?

**Comment by tomasr** [comment]
Dev builds are here: https://ci.appveyor.com/project/tomasr/viasfora/build/artifacts

**Comment by xperiandri** [comment]
That build does not change anything for me
<img width="476" alt="editor margin" src="https://cloud.githubusercontent.com/assets/2365592/9294397/e9e389b0-4454-11e5-90e8-0ebe32c14ae9.png">

**Comment by xperiandri** [comment]
Ah, it is not your functionality.
It is added by [Extensibility Tools 2015](https://visualstudiogallery.msdn.microsoft.com/ab39a092-1343-46e2-b0f1-6a3f91155aa6)
