### ISSUE TITLE
JsonReaderException on VS 2013 startup

### ISSUE THREAD

**Issue by tsasioglu** [tomasr/viasfora#112]
Hi,

I get the VS popup "An exception has been encountered. This may be caused by an extension..." on startup (2013, 2015 seems to work OK). 

ActivityLog.xml:

<entry>
    <record>924</record>
    <time>2015/09/01 08:16:51.147</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: &quot;. Path &apos;[&apos;pricing\pricingmodule.cs&apos;].outlines&apos;, line 4, position 35.&#x000D;&#x000A;   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)&#x000D;&#x000A;   at Newtonsoft.Json.JsonTextReader.ParseProperty()&#x000D;&#x000A;   at Newtonsoft.Json.JsonTextReader.ParseObject()&#x000D;&#x000A;   at Newtonsoft.Json.JsonTextReader.ReadInternal()&#x000D;&#x000A;   at Newtonsoft.Json.JsonTextReader.Read()&#x000D;&#x000A;   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r)&#x000D;&#x000A;   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader)&#x000D;&#x000A;   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)&#x000D;&#x000A;   at Newtonsoft.Json.Linq.JObject.Parse(String json)&#x000D;&#x000A;   at Winterdom.Viasfora.Settings.SolutionUserSettings.TryRead() in c:\projects\viasfora\Viasfora\Settings\SolutionUserSettings.cs:line 92&#x000D;&#x000A;   at Winterdom.Viasfora.Settings.SolutionUserSettings.Load[T](String filePath) in c:\projects\viasfora\Viasfora\Settings\SolutionUserSettings.cs:line 41&#x000D;&#x000A;   at Winterdom.Viasfora.Outlining.UserOutliningManager.LoadRegions(ITextBuffer buffer) in c:\projects\viasfora\Viasfora\Outlining\UserOutliningManager.cs:line 45&#x000D;&#x000A;   at Winterdom.Viasfora.Outlining.UserOutliningManager.&lt;&gt;c__DisplayClass1.&lt;Get&gt;b__0() in c:\projects\viasfora\Viasfora\Outlining\UserOutliningManager.cs:line 17&#x000D;&#x000A;   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)&#x000D;&#x000A;   at Winterdom.Viasfora.Outlining.UserOutliningManager.Get(ITextBuffer buffer) in c:\projects\viasfora\Viasfora\Outlining\UserOutliningManager.cs:line 16&#x000D;&#x000A;   at Winterdom.Viasfora.Outlining.UserOutliningTaggerProvider.CreateTagger[T](ITextBuffer buffer) in c:\projects\viasfora\Viasfora\Outlining\UserOutliningTaggerProvider.cs:line 20&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)</description>
  </entry>

viasfora.xml:

<?xml version="1.0" encoding="utf-8"?>
<viasfora>
	<CurrentLineHighlightEnabled>True</CurrentLineHighlightEnabled>
	<CurrentColumnHighlightEnabled>False</CurrentColumnHighlightEnabled>
	<HighlightLineWidth>1.4</HighlightLineWidth>
	<KeywordClassifierEnabled>False</KeywordClassifierEnabled>
	<EscapeSequencesEnabled>True</EscapeSequencesEnabled>
	<RainbowDepth>4</RainbowDepth>
	<RainbowTagsEnabled>True</RainbowTagsEnabled>
	<RainbowToolTipsEnabled>True</RainbowToolTipsEnabled>
	<RainbowHighlightMode>TrackNextScope</RainbowHighlightMode>
	<DeveloperMarginEnabled>False</DeveloperMarginEnabled>
	<AutoExpandRegions>No</AutoExpandRegions>
	<BoldAsItalicsEnabled>False</BoldAsItalicsEnabled>
	<ModelinesEnabled>True</ModelinesEnabled>
	<ModelinesNumLines>5</ModelinesNumLines>
	<XmlnsPrefixEnabled>True</XmlnsPrefixEnabled>
	<XmlCloseTagEnabled>True</XmlCloseTagEnabled>
	<XmlMatchTagsEnabled>True</XmlMatchTagsEnabled>
	<TextCompletionEnabled>True</TextCompletionEnabled>
	<TCCompleteDuringTyping>False</TCCompleteDuringTyping>
	<TCHandleCompleteWord>False</TCHandleCompleteWord>
	<VB_ControlFlow>goto, resume, throw, exit, stop, do, loop, for, next, for each, with, choose, if, then, else, select, case, switch, call, return, while</VB_ControlFlow>
	<VB_Linq>aggregate, distinct, equals, from, in, group, join, let, order, by, skip, take, where</VB_Linq>
	<VB_Visibility>friend, public, private, protected</VB_Visibility>
	<VB_Enabled>True</VB_Enabled>
	<CSharp_ControlFlow>if, else, while, do, for, foreach, switch, break, continue, return, goto, throw, yield</CSharp_ControlFlow>
	<CSharp_Linq>select, let, where, join, orderby, group, by, on, equals, into, from, descending, ascending</CSharp_Linq>
	<CSharp_Visibility>public, private, protected, internal</CSharp_Visibility>
	<CSharp_Enabled>True</CSharp_Enabled>
	<PresentationModeEnabled>True</PresentationModeEnabled>
	<PresentationModeDefaultZoom>100</PresentationModeDefaultZoom>
	<PresentationModeEnabledZoom>150</PresentationModeEnabledZoom>
	<TextObfuscationRegexes>[]</TextObfuscationRegexes>
</viasfora>

**Comment by tomasr** [comment]
This data is stored in the .suo file for your extension... looks like somehow the file got corrupted or something. I'd love to have a copy of it so that I could examine how that happen if you're able to share it privately (directly email it to me if you can).
Otherwise, you can just delete the .suo file and it should go away....

**Comment by tsasioglu** [comment]
Had a poke around in the .suo (I have both .v11.suo and .v12.suo), and found this in .v12.suo under the VsfUserOptions folder:

{
  "pricing\\pricingmodule.cs": {
    "outlines": {
      "r


Maybe the process was killed while it was writing?

**Comment by tomasr** [comment]
That could definitely be part of the issue. Added some code to silently handle said errors.
