### ISSUE TITLE
System.FormatException after changing system locale decimal symbol

### ISSUE THREAD

**Issue by mmatrosov** [tomasr/viasfora#113]
When trying to load a C++ solution, Visual Studio 2013 spits an error and sends to `ActivityLog.xml`. Here is what I see in this file:

    <entry>
      <record>874</record>
      <time>2015/09/04 15:48:28.165</time>
      <type>Error</type>
      <source>Editor or Editor Extension</source>
      <description>System.FormatException: Input string was not in a correct format.&#x000D;&#x000A;   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)&#x000D;&#x000A;   at System.Convert.ToDouble(String value)&#x000D;&#x000A;   at Winterdom.Viasfora.Settings.VsfSettings.get_HighlightLineWidth() in c:\projects\viasfora\Viasfora\Settings\VsfSettings.cs:line 76&#x000D;&#x000A;   at Winterdom.Viasfora.Text.CurrentColumnAdornment.CreateDrawingObjects() in c:\projects\viasfora\Viasfora\Text\CurrentColumnAdornment.cs:line 118&#x000D;&#x000A;   at Winterdom.Viasfora.Text.CurrentColumnAdornment..ctor(IWpfTextView view, IClassificationFormatMap formatMap, IClassificationType formatType, IVsfSettings settings) in c:\projects\viasfora\Viasfora\Text\CurrentColumnAdornment.cs:line 47&#x000D;&#x000A;   at Winterdom.Viasfora.Text.CurrentColumnAdornmentFactory.&lt;&gt;c__DisplayClass1.&lt;TextViewCreated&gt;b__0() in c:\projects\viasfora\Viasfora\Text\CurrentColumnAdornmentFactory.cs:line 36&#x000D;&#x000A;   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)&#x000D;&#x000A;   at Winterdom.Viasfora.Text.CurrentColumnAdornmentFactory.TextViewCreated(IWpfTextView textView) in c:\projects\viasfora\Viasfora\Text\CurrentColumnAdornmentFactory.cs:line 34&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.&lt;&gt;c__DisplayClassc.&lt;BindContentTypeSpecificAssets&gt;b__9()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)</description>
    </entry>
    <entry>
      <record>875</record>
      <time>2015/09/04 15:48:28.169</time>
      <type>Error</type>
      <source>Editor or Editor Extension</source>
      <description>System.FormatException: Input string was not in a correct format.&#x000D;&#x000A;   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)&#x000D;&#x000A;   at System.Convert.ToDouble(String value)&#x000D;&#x000A;   at Winterdom.Viasfora.Settings.VsfSettings.get_HighlightLineWidth() in c:\projects\viasfora\Viasfora\Settings\VsfSettings.cs:line 76&#x000D;&#x000A;   at Winterdom.Viasfora.Text.CurrentLineAdornment.CreateDrawingObjects() in c:\projects\viasfora\Viasfora\Text\CurrentLineAdornment.cs:line 111&#x000D;&#x000A;   at Winterdom.Viasfora.Text.CurrentLineAdornment..ctor(IWpfTextView view, IClassificationFormatMap formatMap, IClassificationType formatType, IVsfSettings settings) in c:\projects\viasfora\Viasfora\Text\CurrentLineAdornment.cs:line 47&#x000D;&#x000A;   at Winterdom.Viasfora.Text.CurrentLineAdornmentFactory.&lt;&gt;c__DisplayClass1.&lt;TextViewCreated&gt;b__0() in c:\projects\viasfora\Viasfora\Text\CurrentLineAdornmentFactory.cs:line 37&#x000D;&#x000A;   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)&#x000D;&#x000A;   at Winterdom.Viasfora.Text.CurrentLineAdornmentFactory.TextViewCreated(IWpfTextView textView) in c:\projects\viasfora\Viasfora\Text\CurrentLineAdornmentFactory.cs:line 35&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.&lt;&gt;c__DisplayClassc.&lt;BindContentTypeSpecificAssets&gt;b__9()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)</description>
    </entry>

I have been using Viasfora for a couple of weeks and it worked fine. Today I switched "Decimal symbol" under system "Region and Language" -> "Additional settings..." from comma to dot and this starts to happen. When I switch to comma again, all works fine.

**Comment by tomasr** [comment]
Thanks for the report. I issue is I didn't consider number format when persisting the settings file, so when it it was written with one regional setting and you change it, it won't be readable anymore.

Not sure if I can change it to always uses the invariant culture, as that will then break users that are having no problems, but whose settings file got persisted with a different regional setting.

Let me think about it a bit and see how I can fix this without pissing everyone! (in the meantime, you can edit your settings file manually so that it doesn't give you trouble.... it's in c:\users\<user>\Viasfora.xml).

**Comment by mmatrosov** [comment]
Thank you for the quick reply and for the work-around!

As for the fix, you can always try to convert values in two steps. First, try neutral (dot), then try custom (comma). Only if both fails, throw an exception. 

And you should better handle it and report in some meaningful way, because `ActivityLog.xml` is a large document, I was forced into disabling extensions one by one to actually find that Viasfora is causing problems. Then I found it in `ActivityLog.xml`.
