### ISSUE TITLE
Add highlighting for C/C++ format specifiers

### ISSUE THREAD

**Issue by tomasr** [tomasr/viasfora#118]
Requested by Brian Elksworth.

Alternatives:
- Use same highlighting color as for escape sequences (probably simpler)
- Use different highlighting color

**Comment by atypicalbrian** [comment]
If it's not too much of a hassle, could you provide the option to use a different highlighting color? It would be helpful to differentiate between format specifiers and adjacent characters (including escape sequences)

**Comment by tomasr** [comment]
This works now on dev build:
![image](https://cloud.githubusercontent.com/assets/16179/11452542/111f03d2-95b9-11e5-86c6-38fbb5e021b0.png)
