### ISSUE TITLE
Bug: Row/Column Highlight doesn't work on C# Interactive window

### ISSUE THREAD

**Issue by xperiandri** [tomasr/viasfora#121]
Do you do any special integration into Interactive tool windows or this everything works itself?

<img width="1057" alt="interactive windows" src="https://cloud.githubusercontent.com/assets/2365592/11768564/ba24bcf2-a1d9-11e5-9e54-9ef15c877286.png">

**Comment by xperiandri** [comment]
Because as you can see highlight current column works in PowerShell Interactive but does not work in C# interactive.

**Comment by tomasr** [comment]
Great question!

The column/row highlights are tied to TextViews with a role of Document. It could be that the C# interactive one doesn't have that role. I'll see about fixing it.
