### ISSUE TITLE
Disable Italics in Keywords

### ISSUE THREAD

**Issue by tomasr** [tomasr/viasfora#122]
Many people do not like the default italics formatting in flow control keywords, because it cannot be disabled in any way from the VS UI.

**Comment by Mpdreamz** [comment]
:+1:

**Comment by iccfish** [comment]
I like italic flow control keywords...why cannot make it configurable.... :sob:

**Comment by tomasr** [comment]
I love them too, but got tired of people complaining about it all the time grrr....

Unfortunately, while the Visual Studio editor has supported italics since VS2010, no one wants to mess with actually supporting it in the old unmanaged parts of Visual Studio (where the code that handles fonts & colors settings live). Completely sucks.

**Comment by richardcox13** [comment]
Shame as I found this use of italics really nice: a subtle visual reinforcement.

But completely understand the difficulty of working on something with legacy issues...

**Comment by tomasr** [comment]
The only way I can think of doing this with the current limitations would be to have two separate editor formats (i.e. 2 different entries in Fonts & Colors) and then have a setting that tells the classifier which one to use. Seems ugly, though....

**Comment by iccfish** [comment]
I forked project and made some small changes to make this option available in options panel :smile: 

![image](https://cloud.githubusercontent.com/assets/1091653/12150015/efbe3ae4-b4e1-11e5-8a37-2234337fb9cc.png)

Still a little ugly though :joy: 

And I'm thinking of localize this wonderful project :smile:
