### ISSUE TITLE
2.7 breaks closing curly braces detection with interpolated strings in parenthesis

### ISSUE THREAD

**Issue by Suchiman** [tomasr/viasfora#123]
Minimal reproduction:
![2016-01-06_09-33-28](https://cloud.githubusercontent.com/assets/7110884/12138376/bbd181d4-b458-11e5-9803-d16913651f4c.png)
Remove the `$` or remove the `( )` and it will be fine.
This affects for example all method calls that contain interpolated strings.

**Comment by iccfish** [comment]
Yep.....I found this issue.
![image](https://cloud.githubusercontent.com/assets/1091653/12142789/dd49c36e-b4b5-11e5-9d41-ba262831d34e.png)

**Comment by tomasr** [comment]
Fixed this issue. Can you test the updated version before pushing it to the VS Gallery? A build can be found here: https://ci.appveyor.com/project/tomasr/viasfora/build/artifacts

**Comment by iccfish** [comment]
Yep....seems fixed this issue.
Thanks for your work :smiley:
