### ISSUE TITLE
Viasfora resets zoom level

### ISSUE THREAD

**Issue by dogfuntom** [tomasr/viasfora#125]
Visual Studio 2015 remembers and synchronizes zoom level of text editor (without any help from third-party extensions, checked it using SafeMode). But when Viasfora is enabled, the zoom level is 100% in any new tab open and in any restored tab after VS is relaunched.

**Comment by tomasr** [comment]
It only happens when you open a tab right, not with tabs already opened when you changed the zoom level?

**Comment by dogfuntom** [comment]
1. Zoom level in any tab doesn't affect zoom levels of other already open tabs. (But should be synchronized, checked it in SafeMode.)
2. Zoom level in any tab doesn't affect zoom levels of new tabs. (But should be synchronized.)
3. Zoom level doesn't persist when VS is relaunched.

**Comment by tomasr** [comment]
1. works for me
2. Doesn't work, agreed
3. Probably related to 2.

Does it work if you disable Presentation Mode? (Tools -> Options -> Viasfora -> Presentation Mode -> uncheck "Enable Presentation Mode")

**Comment by dogfuntom** [comment]
Yes, it helped, thanks.

**Comment by dogfuntom** [comment]
Probably it should be disabled by default, because it's confusing otherwise.

**Comment by tomasr** [comment]
Did some changes to try to address this, in case you're interested in trying it out. Builds can be found at https://ci.appveyor.com/project/tomasr/viasfora/build/artifacts

**Comment by dogfuntom** [comment]
I confirm, enabled Presentation Mode doesn't cause issues with zoom anymore.
