### ISSUE TITLE
2.7.77 breaks curly braces detection with curly braces inside curly braces inside interpolated strings

### ISSUE THREAD

**Issue by Suchiman** [tomasr/viasfora#128]
![consoleapplication8consoleapplication8_-_microsof_2016-01-11_16-11-40](https://cloud.githubusercontent.com/assets/7110884/12237320/58ac8d04-b87e-11e5-9e97-d6a2e92d939c.png)

**Comment by tomasr** [comment]
Implemented a fix; updated binaries are here: https://ci.appveyor.com/project/tomasr/viasfora/build/artifacts

Can you give them a try and let me know how they work for you?

**Comment by Suchiman** [comment]
Wonderful, seems to work :+1:
Thanks for all your hard work!
