### ISSUE TITLE
Cannot add obfuscation

### ISSUE THREAD

**Issue by somewhatabstract** [tomasr/viasfora#130]
When I go to the Text Hiding options; this is what I see:

![image](https://cloud.githubusercontent.com/assets/1266297/12471157/9509d7ea-bfc0-11e5-81f3-497ec2e4b346.png)

Note that I cannot seem to add a row, nor does it look like the screenshots for the feature. On the occasions where a row is there (which is sometimes the case), I still cannot add an additional row and any information I enter is lost the next time I view the settings.

I am running Visual Studio 2015 Update 1, Windows 10 Pro, and Viasfora 2.7.78

**Comment by tomasr** [comment]
Thanks for reporting this!

I will add explicit buttons for adding/deleting to improve the UI and check why it is not saving changes, but won't be able to get around to it until the weekend!

**Comment by somewhatabstract** [comment]
No problem. Happy to contribute something.

If you need me to verify any changes, please let me know.

**Comment by tomasr** [comment]
I've added some explicit buttons to add/remove entries. Can you give it a try and let me know if it works better/worse?

You can get a dev build from: https://ci.appveyor.com/project/tomasr/viasfora/build/artifacts

**Comment by somewhatabstract** [comment]
Thanks for being patient. Work was hectic. I installed the most recent dev build and tried out the updated settings.

The add button works great and I was able to get the settings to save and obfuscate text. However, the delete button doesn't seem to do anything.

**Comment by tomasr** [comment]
I made a little change; can you verify that works for you?

**Comment by somewhatabstract** [comment]
Thanks again for waiting. I was on vacation.

I have installed the latest VSIX from Appveyor and everything seems to be working for Text Hiding now.

Thanks!

**Comment by tomasr** [comment]
Awesome, thanks!
