### ISSUE TITLE
Visual Studio crashes when hovering over a collapsed region

### ISSUE THREAD

**Issue by PachowStudios** [tomasr/viasfora#132]
This will only happen when Viasfora is installed. Disabling it fixes the issue.

The fatal error in the activity log is as such:
```
<entry>
  <record>179</record>
  <time>2016/02/15 23:44:32.157</time>
  <type>Error</type>
  <source>Color Theme Service</source>
  <description>The color 'Popup' in category 'de7b1121-99a4-4708-aedf-15f40c9b332f' does not exist.</description>
</entry>
```

**Comment by tomasr** [comment]
Thanks for the report! Can you give me more details?
* Visual Studio version
* Does it happen in any specific language? C#? VB? Other?
* I'm assuming you mean hovering the mouse over the '...'?

**Comment by tomasr** [comment]
I think I can repro it, but in my case I don't see any exceptions; VS just seems to sort of hang.

**Comment by tomasr** [comment]
I've pushed an updated build to the VS Gallery with the fix. Let me know if it happens again!

**Comment by PachowStudios** [comment]
Looks like that fixed it! Thanks for being so fast! :100:
