### ISSUE TITLE
High CPU / Lag

### ISSUE THREAD

**Issue by MrThing** [tomasr/viasfora#133]
There is high CPU usage and general lag when switching between open files. I finally was able to narrow it down to your plugin, after hunting through my extensions.

I would really like to tell you what specific operation was causing this, but it seems like when the document is "visible", your plugin does a scan of the text and is thus causing lagging. Any operations like expanding a section will gray out the screen and say that VS is not responding. 

Is there some sort of logging that I could show, that would help you debug this?

**Comment by tomasr** [comment]
Can you tell me a bit more about this?

* What VS version is this?
* What kind of files do you have opened? (C#, html, razor files, etc)
* What other VS extensions do you have running?

I have not seen this, and the things that do scan text in Viasfora are highly optimized to deal even with files with 10s of 1000s of lines of code.

The way to troubleshoot this would be to capture an ETW trace with PerfView (https://www.microsoft.com/en-us/download/details.aspx?id=28567) like this:
* Start the trace
* Switch to VS and reproduce the issue a couple of times
* Stop the trace

Make sure the "Zip" box in the collection dialog is enabled when you do this, then share the resulting ZIP file with me...
