### ISSUE TITLE
Error loading Winterdom.Viasfora assembly

### ISSUE THREAD

**Issue by MarkSky** [tomasr/viasfora#141]
I use Visual Studio Community 2015.
Today, I updated Viasfora to the version 3.0.96, and when I edit the css file, the vs2015 showed me there is an error, and asked me to see the ActivityLog.xml, and I got an error information:
`<entry>
    <record>528</record>
    <time>2016/04/07 02:31:30.258</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.IO.FileNotFoundException: Could not load file or assembly &apos;Winterdom.Viasfora, Culture=neutral&apos; or one of its dependencies. &#x7CFB;&#x7D71;&#x627E;&#x4E0D;&#x5230;&#x6307;&#x5B9A;&#x7684;&#x6A94;&#x6848;&#x3002;&#x000D;&#x000A;&#x6A94;&#x6848;&#x540D;&#x7A31;: &apos;Winterdom.Viasfora, Culture=neutral&apos;&#x000D;&#x000A;   &#x65BC; System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   &#x65BC; System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   &#x65BC; System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   &#x65BC; System.Reflection.Assembly.Load(AssemblyName assemblyRef)&#x000D;&#x000A;   &#x65BC; System.Windows.Navigation.BaseUriHelper.GetLoadedAssembly(String assemblyName, String assemblyVersion, String assemblyKey)&#x000D;&#x000A;   &#x65BC; MS.Internal.AppModel.ResourceContainer.GetResourceManagerWrapper(Uri uri, String&amp; partName, Boolean&amp; isContentFile)&#x000D;&#x000A;   &#x65BC; MS.Internal.AppModel.ResourceContainer.GetPartCore(Uri uri)&#x000D;&#x000A;   &#x65BC; System.IO.Packaging.Package.GetPartHelper(Uri partUri)&#x000D;&#x000A;   &#x65BC; System.IO.Packaging.Package.GetPart(Uri partUri)&#x000D;&#x000A;   &#x65BC; System.IO.Packaging.PackWebResponse.CachedResponse.GetResponseStream()&#x000D;&#x000A;   &#x65BC; System.IO.Packaging.PackWebResponse.GetResponseStream()&#x000D;&#x000A;   &#x65BC; System.IO.Packaging.PackWebResponse.get_ContentType()&#x000D;&#x000A;   &#x65BC; System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid&amp; clsId, Boolean&amp; isOriginalWritable, Stream&amp; uriStream, UnmanagedMemoryStream&amp; unmanagedMemoryStream, SafeFileHandle&amp; safeFilehandle)&#x000D;&#x000A;   &#x65BC; System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)&#x000D;&#x000A;   &#x65BC; System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()&#x000D;&#x000A;   &#x65BC; System.Windows.Media.Imaging.BitmapImage.EndInit()&#x000D;&#x000A;   &#x65BC; System.Windows.Media.Imaging.BitmapImage..ctor(Uri uriSource, RequestCachePolicy uriCachePolicy)&#x000D;&#x000A;   &#x65BC; Winterdom.Viasfora.Intellisense.PlainTextCompletionSource..ctor(ITextBuffer buffer, ITextStructureNavigator structureNavigator, IVsfSettings settings)&#x000D;&#x000A;   &#x65BC; Winterdom.Viasfora.Intellisense.PlainTextCompletionSourceProvider.TryCreateCompletionSource(ITextBuffer textBuffer)&#x000D;&#x000A;   &#x65BC; Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionBroker.&lt;&gt;c__DisplayClass37_0.&lt;CreateSourcesForBuffer&gt;b__0(ICompletionSourceProvider provider)&#x000D;&#x000A;   &#x65BC; Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeMatchingFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, Object errorSource)&#x000D;&#x000A;&#x000D;&#x000A;&#x8B66;&#x544A;: &#x7D44;&#x4EF6;&#x7E6B;&#x7D50;&#x8A18;&#x9304;&#x5207;&#x63DB;&#x70BA; OFF&#x3002;&#x000D;&#x000A;&#x82E5;&#x8981;&#x8A18;&#x9304;&#x7D44;&#x4EF6;&#x7E6B;&#x7D50;&#x5931;&#x6557;&#xFF0C;&#x8ACB;&#x5C07;&#x767B;&#x9304;&#x503C; [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) &#x8A2D;&#x70BA; 1&#x3002;&#x000D;&#x000A;&#x6CE8;&#x610F;: &#x8207;&#x7D44;&#x4EF6;&#x7E6B;&#x7D50;&#x5931;&#x6557;&#x8A18;&#x9304;&#x76F8;&#x95DC;&#x7684;&#x6548;&#x80FD;&#x6703;&#x6709;&#x90E8;&#x5206;&#x8CA0;&#x9762;&#x5F71;&#x97FF;&#x3002;&#x000D;&#x000A;&#x82E5;&#x8981;&#x95DC;&#x9589;&#x6B64;&#x529F;&#x80FD;&#xFF0C;&#x8ACB;&#x79FB;&#x9664;&#x767B;&#x9304;&#x503C; [HKLM\Software\Microsoft\Fusion!EnableLog]&#x3002;&#x000D;&#x000A;</description>
  </entry>`

How could I solve the problem?
Thanks.

**Comment by FutureTD** [comment]
Visual Studio Enterprise 2015

I am receiving the exact same error.

**Comment by tomasr** [comment]
This looks like the Visual Studio Component Cache got messed up somehow. Can you try this?

* Close Visual Studio
* Open an explorer window to ```%localappdata%\Microsoft\VisualStudio\14.0\ComponentModelCache````
* Delete this folder
* Start Visual Studio again

This should clear the cache and resolve the issue.

Alternatively, you could use the [Clear MEF Component Cache](https://visualstudiogallery.msdn.microsoft.com/22b94661-70c7-4a93-9ca3-8b6dd45f47cd) extension from Mads Kristensen, which adds an UI command to do the same.

**Comment by FutureTD** [comment]
I tried both of the options suggested and still getting the error:

<entry>
    <record>831</record>
    <time>2016/04/07 12:45:31.793</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.IO.FileNotFoundException: Could not load file or assembly &apos;Winterdom.Viasfora, Culture=neutral&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Winterdom.Viasfora, Culture=neutral&apos;&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)&#x000D;&#x000A;   at System.Windows.Navigation.BaseUriHelper.GetLoadedAssembly(String assemblyName, String assemblyVersion, String assemblyKey)&#x000D;&#x000A;   at MS.Internal.AppModel.ResourceContainer.GetResourceManagerWrapper(Uri uri, String&amp; partName, Boolean&amp; isContentFile)&#x000D;&#x000A;   at MS.Internal.AppModel.ResourceContainer.GetPartCore(Uri uri)&#x000D;&#x000A;   at System.IO.Packaging.Package.GetPartHelper(Uri partUri)&#x000D;&#x000A;   at System.IO.Packaging.Package.GetPart(Uri partUri)&#x000D;&#x000A;   at System.IO.Packaging.PackWebResponse.CachedResponse.GetResponseStream()&#x000D;&#x000A;   at System.IO.Packaging.PackWebResponse.GetResponseStream()&#x000D;&#x000A;   at System.IO.Packaging.PackWebResponse.get_ContentType()&#x000D;&#x000A;   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid&amp; clsId, Boolean&amp; isOriginalWritable, Stream&amp; uriStream, UnmanagedMemoryStream&amp; unmanagedMemoryStream, SafeFileHandle&amp; safeFilehandle)&#x000D;&#x000A;   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)&#x000D;&#x000A;   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()&#x000D;&#x000A;   at System.Windows.Media.Imaging.BitmapImage.EndInit()&#x000D;&#x000A;   at System.Windows.Media.Imaging.BitmapImage..ctor(Uri uriSource, RequestCachePolicy uriCachePolicy)&#x000D;&#x000A;   at Winterdom.Viasfora.Intellisense.PlainTextCompletionSource..ctor(ITextBuffer buffer, ITextStructureNavigator structureNavigator, IVsfSettings settings)&#x000D;&#x000A;   at Winterdom.Viasfora.Intellisense.PlainTextCompletionSourceProvider.TryCreateCompletionSource(ITextBuffer textBuffer)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionBroker.&lt;&gt;c__DisplayClass37_0.&lt;CreateSourcesForBuffer&gt;b__0(ICompletionSourceProvider provider)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeMatchingFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, Object errorSource)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
  </entry>

**Comment by tomasr** [comment]
Ahh, OK, I can repro it now.... it only kicks in when Plain-Text completion gets activated. Try disabling the "Complete during Typing" option in Tools -> Options -> Viasfora -> Intellisense if you have that enabled meanwhile to prevent the error from popping up.

Working on fixing it and will push an update later today.

**Comment by tomasr** [comment]
Another related issue is that the options page for the text obfuscation feature is not loading either.

**Comment by tomasr** [comment]
Updated release 3.0.98 to the Visual Studio Gallery with the fix
