### ISSUE TITLE
Incorrect Border Color when Rainbow Depth is Less Than 9

### ISSUE THREAD

**Issue by VPhamHTX** [tomasr/viasfora#142]
If the **Rainbow Depth** option is not set to 9, the border color that shows **when holding the CTRL key** (Windows) will not match the brace color for braces after the **Rainbow Depth**.

Ex.
If **Rainbow Depth** = 4, the border for 5th brace and above will show the color as if **Rainbow Depth** was set to 9, instead of looping through the first 4.

**Edit:**
In Viasfora.Rainbow/RainbowHighlight.cs, the GetRainbowBrush function:
var rainbow = rainbowTags[depth % **rainbowTags.Length**]

should be 

var rainbow = rainbowTags[depth % **this.provider.Settings.RainbowDepth**]

**Comment by tomasr** [comment]
Thanks for the report! I had noticed that one before, but it slipped my mind, somehow.

Speaking of which, any particular reason why you like to use a smaller depth? (I've considered removing the option, but this gives me better clues of how people are using it!)

**Comment by VPhamHTX** [comment]
For me, (at one point), I had set it to 4, and set the colors to the original 4 colors mainly because that's what it started out with and I preferred the original colors. I don't mind either way, but I'd rather have the option to change it.
