### ISSUE TITLE
viasfora and C# outline

### ISSUE THREAD

**Issue by cato541265** [tomasr/viasfora#143]
After installing viasfora result in C # outline 2012/2013/2015 plug function failure,I hope you will find the problem.

**Comment by tomasr** [comment]
Can you explain a bit more what you mean? Are you referring to using any particular Viasfora feature?

**Comment by cato541265** [comment]
I installed Visual Studio 2012/2013/2015 tool C # outline 2012/2013/2015
After the plug-in feature for C # code folding but installed viasfora C # outline code folding function becomes ineffective.(I use Google translate because my English is very poor if not expressed clearly I'm sorry)

**Comment by tomasr** [comment]
I think I may know what you mean..... you mean the [-] symbols that allow you to collapse functions, classes and things like that don't appear anymore? If so, that is one viasfora feature that is optional.

In Tools -> Options -> Viasfora, try changing the option named "Expand Regions on Open" (make sure it is not set to "Disable":

![image](https://cloud.githubusercontent.com/assets/16179/14413644/db2c821c-ff45-11e5-84a7-9fc51995aed4.png)

**Comment by cato541265** [comment]
Thank you very much for your answer
But did not solve my problems
Useless viasfora （Use C# online plug-in）
![default](https://cloud.githubusercontent.com/assets/5895179/14414561/5dd5e2c2-ffc7-11e5-9218-b0ca206d2f45.png)
With viasfora （Use C# online plug-in）
![default](https://cloud.githubusercontent.com/assets/5895179/14414578/ab955cea-ffc7-11e5-9263-51b110d85513.png)

**Comment by tomasr** [comment]
Great, that actually clarifies things a lot! It seems like it might be a conflict with another extension!

Do you have Visual Studio 2015 Power Tools installed?

**Comment by cato541265** [comment]
I install tool
![11](https://cloud.githubusercontent.com/assets/5895179/14414909/ef9be4a0-ffcb-11e5-8262-d32af6c104e2.png)
![22](https://cloud.githubusercontent.com/assets/5895179/14414910/efcb13c4-ffcb-11e5-9be7-e07553da340d.png)
 I don't know Power Tools

I guess viasfora  with C # Outline 2012 conflict
I use visual studio 2012/2013/2015 have the same problem.

**Comment by tomasr** [comment]
Excellent! I will install that one and check what can be done about it!

**Comment by tomasr** [comment]
I knew this seemed familiar....... This was brought up a few years ago, and here's what I noted about it:

I've been looking at this, and it is directly related to the changes in Rainbow Braces. Basically, when I changed it from a view-level tagger, to a buffer-level tagger, it broke the C# Outliner (it causes it to see the tag spans returned by Viasfora).

> That said, I'm still not entirely sure what exactly is it that breaks it, as it doesn't look at the actual classification type. I *think* the issue might be that it looks at the character at the end of the TagSpan, rather than the start (and that is going to be totally off, because the spans returned by Viasfora start right at the brace, but do not *end* at the brace).
> So I still think this is basically a problem in how the C# Outliner extension actually works; and not much I can actually do on my end to fix it, short of moving the Rainbow Brace tagger to be view-level, but that would impact performance and complicate a bunch of other things :/

From what I now remember, fixing this should be a relatively trivial fix in the C# Outliner implementation. I would be worth contacting the author and pointing them to this response to see if maybe they are willing to fix it....

Sorry for not having better news :disappointed:

**Comment by VPhamHTX** [comment]
If you have Visual Studio 2015, there is another addon similar to C# Outliner.
https://visualstudiogallery.msdn.microsoft.com/699ecb9d-bd8f-4f6b-b290-05c42407b43e
