### ISSUE TITLE
Rainbow Braces: Issue or Feature Request for string interpolation

### ISSUE THREAD

**Issue by kgallaha** [tomasr/viasfora#147]
**Observation:**
Viasfora doesn't currently format the color of braces contained within string interpolations such as:
`$"These {braces} aren't colored at {all}"`

**Issue or Feature Request:**
These braces should be colored

**Comment by tomasr** [comment]
This has been supported since v2.7.... what version are you using? If a newer one, can you clarify exactly what is not working for you?

**Comment by kgallaha** [comment]
Ah, I just realized that the coloring is only absent if you are using a string literal.  So instead the snippet should have been 
`$@"String {litterals} aren't colored inside a {regex}"`

**Comment by tomasr** [comment]
Just did an initial attempt at solving this. Can you check the dev build at https://ci.appveyor.com/project/tomasr/viasfora/build/artifacts and see if that works better for you?

Thanks for reporting this!

**Comment by kgallaha** [comment]
Almost fixed.  The particular string being interpolated where I noticed this is as follows:

`newPath = $@"{newDirectory}\{newFileName} ({i++}){newFileExtension}";`

The second set of braces {newFileName} is not getting colored - perhaps because a '\' character proceeds it which is being interpreted as an escape character?

**Comment by tomasr** [comment]
Nice catch!

New version should be up on AppVeyor fixing this. Let me know if this one works better!

**Comment by kgallaha** [comment]
All seems well here now, thanks for the quick fix.
