### ISSUE TITLE
Feature Request: Option to assign a color to Closing Tag Prefix or match assigned color

### ISSUE THREAD

**Issue by kgallaha** [tomasr/viasfora#148]
This is a feature request related to the existing XML color options:

- XML Closing Tag
- XML Prefix

My current use case it to essentially 'grey out' closing XML tags using Viasfora.  However, the XML Prefix color option is still applied to closing tags.

I'd like one or both of the following options

- Assign separate color to XML Closing Tag Prefixes
- Checkbox to Match XML Closing Tag Prefix to to XML Closing Tag color

**Comment by tomasr** [comment]
Implemented this by adding a new classifier type called "Viasfora XML Prefix Closing". You can change it through Font & Colors as usual.

Give it a whirl and see if it does what you need.

**Comment by kgallaha** [comment]
Installed 3.0.104 - the option is available however changing the color doesn't appear to have any affect.  

Restarted VS, closed opened XML (XAML) file, opened different project with different XML files.

**Comment by tomasr** [comment]
Not sure what you're seeing; seems to be working just fine for me:
![vsf-colors](https://cloud.githubusercontent.com/assets/16179/14660441/07797f38-066b-11e6-9c31-2a38fe26184c.gif)

Are you seeing something different? What VS version are you using?

**Comment by kgallaha** [comment]
![vsversion](https://cloud.githubusercontent.com/assets/5379488/14660827/a9c253cc-0676-11e6-84ca-f589bd7f2ae8.PNG)
![viasforaversion](https://cloud.githubusercontent.com/assets/5379488/14660832/aebc6d9a-0676-11e6-81f5-78be1d61f357.PNG)
![prefixoption](https://cloud.githubusercontent.com/assets/5379488/14660834/b3657bde-0676-11e6-8b63-215935c4dbe4.PNG)
![prefixcolor](https://cloud.githubusercontent.com/assets/5379488/14660836/b4dfa7d2-0676-11e6-818e-eefc198d3796.PNG)

**Comment by tomasr** [comment]
Ahh, you should've mentioned that you were working on a XAML document (which is actually an entirely separate editor from the normal XML editor, for some reason). Let me try to fix that.

**Comment by kgallaha** [comment]
I did but without much emphasis:
> Restarted VS, closed opened XML (XAML) file, opened different project with different XML files.

Didn't realize these are targeted differently since the first two XML options worked fine.

**Comment by tomasr** [comment]
Next build should be available in a few minutes. Let me know how this one works.

**Comment by kgallaha** [comment]
Looks good, thanks for another quick implementation.

**Comment by tomasr** [comment]
Thanks you for having patience; sometimes miss details :smile:
