### ISSUE TITLE
Can't get 3.1.106 to stay enabled.

### ISSUE THREAD

**Issue by davidn-sytelco** [tomasr/viasfora#152]
I can't get version 3.1.106 on Visual Studio 2015 Update 2 to stay enabled.  I can enable it and select to restart Visual Studio and it will work, but after closing and opening Visual Studio again it is switched back to disabled.  Anyone else having this?  What should I do to collect useful information about what is going on?

**Comment by tomasr** [comment]
Can you try enabling logging on that second restart where it gets disabled? Instead of starting VS as usual, run ```devenv /log```, ensure it starts disabled, then close VS again and share the ```%APPDATA%\Microsoft\VisualStudio\14.0\ActivityLog.xml``` file to see if there's anything in there related!

You could also try running ```devenv /ResetSkipPkgs``` to remove all info about disabled packages....

**Comment by davidn-sytelco** [comment]
[ActivityLog.zip](https://github.com/tomasr/viasfora/files/257268/ActivityLog.zip)

Looks like it has an ID clash with another extension.

**Comment by tomasr** [comment]
I think you somehow ended up with two copies of Viasfora in 2 separate paths.

Can you check the following paths?

- ```C:\USERS\DAVID\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\2TZ2XVBK.KC5\```
- ```C:\USERS\DAVID\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\XI5TJU4Q.XNS\```

And see what is there?

**Comment by davidn-sytelco** [comment]
Both had 3.1.106 in them.  I had to uninstall twice, then install and now it is fine again.

Thanks for the help!  Viasfora is one of my must have essential extensions :-)
