### ISSUE TITLE
Serious performance problem when amount of output is substantial

### ISSUE THREAD

**Issue by konste** [tomasr/viasfora#153]
I like your Viasfora, but unfortunately it happened to be a culprit of VS build performance problem which was hurting us for some time. It seems that when amount of the text in the output window grows beyond any trivial size Viasfora becomes the bottleneck and slows the build down to almost hung. As a repro you may try to build any substantially sized solution while setting output verbosity to diagnostic and of course having Viasfora turned On. Very soon you will see Output window frozen and Windows Resource Monitor shows that only one thread in VS is running. Profiler points to Viasfora as a culprit and indeed after disabling it build speed restores to normal. Please take a look and at least acknowledge the problem so that I know it is not my head. If you find a way to fix it that would be great and we would be able to use it again.

**Comment by tomasr** [comment]
I'm happy to take a look, you're the first one reporting this.

Can you clarify a few things?
- What version of VS are you using?
- What viasfora features do you have turned on?

Tomas Restrepo
http://winterdom.com/

**Comment by konste** [comment]
I'm very glad to hear from you!

VS 2015 Enterprise with Update 2 and all "micro" updates installed.

Regarding Viasfora features it is easy - default.

I hope the repro is as easy as big solution which normally builds on all cores. With output verbosity set to Diagnostic only one core seems to be loaded and the build takes ten fold more time. Output window looks kind of frozen - refresh happens, but rarely.

Let me know if you have problem reproducing the problem :-) I'm very interested to get to the bottom of it and do what I can.

Konstantin
< sent from mobile device >

On May 28, 2016, at 1:29 PM, Tomas Restrepo <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm happy to take a look, you're the first one reporting this.

Can you clarify a few things?
- What version of VS are you using?
- What viasfora features do you have turned on?

Tomas Restrepo
http://winterdom.com/

On Sat, May 28, 2016 at 2:22 PM, Konstantin Erman <notifications@github.com<mailto:notifications@github.com>>
wrote:

> I like your Viasfora, but unfortunately it happened to be a culprit of VS
> build performance problem which was hurting us for some time. It seems that
> when amount of the text in the output window grows beyond any trivial size
> Viasfora becomes the bottleneck and slows the build down to almost hung. As
> a repro you may try to build any substantially sized solution while setting
> output verbosity to diagnostic and of course having Viasfora turned On.
> Very soon you will see Output window frozen and Windows Resource Monitor
> shows that only one thread in VS is running. Profiler points to Viasfora as
> a culprit and indeed after disabling it build speed restores to normal.
> Please take a look and at least acknowledge the problem so that I know it
> is not my head. If you find a way to fix it that would be great and we
> would be able to use it again.
>
> -
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tomasr/viasfora/issues/153>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAA_Mw93PS5RReWCzyVAY6QblV-EnX3dks5qGJYGgaJpZM4IpJEA>
> .
>

-

**Comment by tomasr** [comment]
I think I figured out what is going on. Can you try the latest build from https://ci.appveyor.com/project/tomasr/viasfora/build/artifacts and let me know if it fixes the issue for you?

**Comment by konste** [comment]
Will certainly do within the next hour!

**Comment by konste** [comment]
Yes, that was it! I understand it is a little too late to say “I knew it”, but I really expected somethings like scan for braces in huge Outputs.

Thank you!
Konstantin

**Comment by tomasr** [comment]
Awesome, thanks! I'll get this out on the next release as soon as possible :)

**Comment by konste** [comment]
Curious why it is updated on http://vsixgallery.com/extension/Winterdom.Viasfora.f7a33795-2b40-4125-856c-89b0bd8cd5ab/
And not updated on https://visualstudiogallery.msdn.microsoft.com/19609469-380e-4fcf-bcde-e31caeb658b2 ?

**Comment by tomasr** [comment]
Because there are still a couple more changes I want to get in before releasing v3.2 officially. You can always install directly from the vsixgallery feed, in which case you'd get updates everytime I push changes to the develop branch.
