### ISSUE TITLE
Handles interpolated verbatim strings wrong

### ISSUE THREAD

**Issue by Suchiman** [tomasr/viasfora#154]
```csharp
class Program
{
    static void Main()
    {
        string test = $@"
class Program
{{
    static void Main()
    {{
        Console.WriteLine(""test"");
    }}
}}";
    }
}
```
![devenv_2016-05-29_00-36-03](https://cloud.githubusercontent.com/assets/7110884/15630305/62cbbfac-2535-11e6-846b-0fc060d7fefd.png)

**Comment by tomasr** [comment]
This should be fixed in the latest dev build now. Thanks for the report!
