### ISSUE TITLE
Visual Studio crashes when searching text

### ISSUE THREAD

**Issue by bfranklin825** [tomasr/viasfora#155]
I'm running VS2015 v 14.0.25123.00 Update 2 with .NET framework 4.6.01038

Every time I do a search for text - any text, in any sort of file - Viasfora causes VS to crash. If I uninstall Visafora my text search works just fine.

**Comment by bfranklin825** [comment]
Faulting application name: devenv.exe, version: 14.0.25123.0, time stamp: 0x56f22f32
Faulting module name: windows.globalization.dll, version: 10.0.10586.0, time stamp: 0x5632d553
Exception code: 0xc0000005
Fault offset: 0x00038d92
Faulting process id: 0xa788
Faulting application start time: 0x01d1bb429068952d
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
Faulting module path: C:\Windows\SYSTEM32\windows.globalization.dll
Report Id: 625e02ae-d0c3-48f7-aa40-72969982309f
Faulting package full name: 
Faulting package-relative application ID:

**Comment by tomasr** [comment]
Thanks for the report, @bfranklin825.

I have not seen this one before; I will try to reproduce it.
Are you seeing any exception error being written to the ActivityLog before the crash?

**Comment by bfranklin825** [comment]
This may have been premature... I just uninstalled a spell checker extension that I had and now it seems to be working properly? I don't know what the deal is - maybe they don't play well together? But it runs fine with either installed but crashes when both are installed. I'd rather have Viasfora than the spell checker. 

Spell Checker by Roman Golovin, Michael Lehenl, Version 2.26... was the one I had installed. 

Going to try a different spell checker.

**Comment by bfranklin825** [comment]
Another crash when both are installed is from the word breaker dll...

Faulting application name: devenv.exe, version: 14.0.25123.0, time stamp: 0x56f22f32
Faulting module name: MSWB7.dll, version: 10.0.10586.0, time stamp: 0x5632d70d
Exception code: 0xc0000005
Fault offset: 0x0000ee22
Faulting process id: 0xd2a4
Faulting application start time: 0x01d1bb40e6b6ae30
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
Faulting module path: C:\Windows\System32\MSWB7.dll
Report Id: 5471a8f8-cd51-41f4-aa02-2d26c346198c
Faulting package full name: 
Faulting package-relative application ID:

**Comment by bfranklin825** [comment]
Installed Visual Studio Spell Checker by EWSoftware v 2016.5.28.0 and it and VIasfora seem to work just fine together.

**Comment by tomasr** [comment]
Excellent information, thanks @bfranklin825. I'll try to repro later today and try to get to the bottom of it.
