### ISSUE TITLE
Possible to change colors for control control keywords?

### ISSUE THREAD

**Issue by rharmaning** [tomasr/viasfora#157]
Like this extension a lot - only thing I'd change if I could would be the redorange color of the control flow keywords, which at least to my eyes look like compile errors which end up slowing down my code reading instead of speeding it up like the color-coded brackets do!

Anyway to change these if even to a less-vibrant hue?

Thanks!

**Comment by tomasr** [comment]
You can already change the color both from the general Fonts & Colors dialog in VIsual Studio, as well as from the Viasfora options dialogs.... what is the problem?

**Comment by rharmaning** [comment]
My inability to see the Viasfora options :) Found exactly what I needed - thanks!
