### ISSUE TITLE
Separate brace coloring by type

### ISSUE THREAD

**Issue by zakirshikhli** [tomasr/viasfora#158]
Are there an option to set separate brace coloring by type, to begin and end independently with each other.

 For EX:
1st level "{" is **red**
1st level "(" is **red** too
2nd level "(" is **orange**
1st level "[" is **red** again
3rd level "(" is **green** etc.

Because I always confuse same brace types on code end.

**Comment by tomasr** [comment]
Not at this time, but it is something a few people have asked about. I'm looking into how to provide this.

**Comment by tomasr** [comment]
Added support for this through a new option; disabled by default.

**Comment by zakirshikhli** [comment]
Thank You very much! It's a big help for me, my friend.
