### ISSUE TITLE
Changing initial configuration of Viasfora lets crash VS2015 on startup

### ISSUE THREAD

**Issue by MartinL0815** [tomasr/viasfora#159]
I just installed Viasfora in VS2015 and configured it the same way it was configured in VS2013.

Now VS2015 crashes on Startup!

In ist activity log the following lines describe Viasfora related Errors:
> 161  Entering function CVsPackageInfo::HrInstantiatePackage {F419E6BB-F72F-42CF-ACFE-D0D0E17FCB17}  VisualStudio 2016/07/04 12:28:00.578 
> 162  Begin package load [Microsoft.VisualStudio.Shell.VsHubServicePackage] {F419E6BB-F72F-42CF-ACFE-D0D0E17FCB17}  VisualStudio 2016/07/04 12:28:00.578 
> 163 ERROR Still unable to load MEF component DLL: Could not load file or assembly 'Microsoft.CSS.Editor, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
>           C:\windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.VisualStudio.JavaScript.Project\v4.0_14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.JavaScript.Project.dll   Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost 2016/07/04 12:28:00.651 
> 164 ERROR Still unable to load MEF component DLL: Could not load file or assembly 'Microsoft.VisualStudio.Workspaces.Contracts, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
>           C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\DGWQ5VGT.MHG\TMLanguage.dll   Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost 2016/07/04 12:28:02.761 
> 165 ERROR Error loading extension: This VSIX does not apply to any product installed on this machine. The problem could be that the VSIX manifest's format is not recognized, or that the manifest has been corrupted. Data at the root level is invalid. Line 1, position 1. 
>           C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\MICROSOFT\VSGRAPHICS\   Extension Manager 2016/07/04 12:28:02.866 
> 166 ERROR Error loading extension: This VSIX does not apply to any product installed on this machine. The problem could be that the VSIX manifest's format is not recognized, or that the manifest has been corrupted. Data at the root level is invalid. Line 1, position 1. 
>           C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\MICROSOFT\VSGRAPHICS\   Extension Manager 2016/07/04 12:28:02.993 
> 167 ERROR An item with the same key has already been added.   Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost 2016/07/04 12:28:10.848 
> 168 ERROR Still unable to load MEF component DLL: Could not load file or assembly 'Microsoft.CSS.Editor, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
>           C:\windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.VisualStudio.JavaScript.Project\v4.0_14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.JavaScript.Project.dll   Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost 2016/07/04 12:28:10.873 
> 169 ERROR Still unable to load MEF component DLL: Could not load file or assembly 'Microsoft.VisualStudio.Workspaces.Contracts, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
>           C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\DGWQ5VGT.MHG\TMLanguage.dll   Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost 2016/07/04 12:28:10.873 
> 170 ERROR An item with the same key has already been added.   Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost 2016/07/04 12:28:14.207 
> 171 ERROR LegacySitePackage failed for package [Winterdom.Viasfora.VsfPackage, Viasfora, Version=2.5.0.0, Culture=neutral, PublicKeyToken=null]Source: 'mscorlib' Description: Exception has been thrown by the target of an invocation. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: An item with the same key has already been added. at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) at Microsoft.VisualStudio.ExtensibilityHosting.VsExportProviderFactory.<>c__DisplayClass54_0.<CreateAssemblyCatalogsAsync>b__6(KeyValuePair`2 namedCatalog) at System.Threading.Tasks.Dataflow.ActionBlock`1.ProcessMessage(Action`1 action, KeyValuePair`2 messageWithId) at System.Threading.Tasks.Dataflow.ActionBlock`1.<>c__DisplayClass5.<.ctor>b__0(KeyValuePair`2 messageWithId) at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.ExtensibilityHosting.VsExportProviderFactory.<CreateAssemblyCatalogsAsync>d__54.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at Microsoft.VisualStudio.ExtensibilityHosting.VsExportProviderFactory.<GetCurrentAssemblyCatalogsAsync>d__31.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.ExtensibilityHosting.VsExportProviderFactory.<GetExportProviderFactoryAsync>d__23.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.<GetMEFV3ExportProviderInternalAsync>d__49.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.<GetMEFV3ExportProviderWrapperAsync>d__48.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread() at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread() at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions) at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod) at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetLazyValue[T](AsyncLazy`1 lazy) at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]() --- End of inner exception stack trace --- at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at Winterdom.Viasfora.Compatibility.SComponentModel.GetService[T]() at Winterdom.Viasfora.Telemetry.Initialize(DTE2 dte) at Winterdom.Viasfora.VsfPackage.InitializeTelemetry() at Winterdom.Viasfora.VsfPackage.Initialize() at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)System.ArgumentException: An item with the same key has already been added. at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) at Microsoft.VisualStudio.ExtensibilityHosting.VsExportProviderFactory.<>c__DisplayClass54_0.<CreateAssemblyCatalogsAsync>b__6(KeyValuePair`2 namedCatalog) at System.Threading.Tasks.Dataflow.ActionBlock`1.ProcessMessage(Action`1 action, KeyValuePair`2 messageWithId) at System.Threading.Tasks.Dataflow.ActionBlock`1.<>c__DisplayClass5.<.ctor>b__0(KeyValuePair`2 messageWithId) at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.ExtensibilityHosting.VsExportProviderFactory.<CreateAssemblyCatalogsAsync>d__54.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at Microsoft.VisualStudio.ExtensibilityHosting.VsExportProviderFactory.<GetCurrentAssemblyCatalogsAsync>d__31.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.ExtensibilityHosting.VsExportProviderFactory.<GetExportProviderFactoryAsync>d__23.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.<GetMEFV3ExportProviderInternalAsync>d__49.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.<GetMEFV3ExportProviderWrapperAsync>d__48.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread() at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread() at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions) at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod) at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetLazyValue[T](AsyncLazy`1 lazy) at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]() {3338742C-7926-4949-9E57-3FCBB8D0A976} 80131604 VisualStudio 2016/07/04 12:28:14.240 
> 172 ERROR SetSite failed for package [Winterdom.Viasfora.VsfPackage, Viasfora, Version=2.5.0.0, Culture=neutral, PublicKeyToken=null](null) {3338742C-7926-4949-9E57-3FCBB8D0A976} 80131604 VisualStudio 2016/07/04 12:28:14.246 
> 173 ERROR End package load [Winterdom.Viasfora.VsfPackage, Viasfora, Version=2.5.0.0, Culture=neutral, PublicKeyToken=null] {3338742C-7926-4949-9E57-3FCBB8D0A976} 80131604 VisualStudio 2016/07/04 12:28:14.250 

Now I have some questions:
1. How to get VS2015 running again (without Viasfora)?
2. How to get VS2015 running with Viasfora?
3. Where to find the changed configuration to send it to you to Support you to Support me?

Cheers,

Martin

**Comment by tomasr** [comment]
Hi Martin,

You don't need to customize separately Viasfora for different versions of VS installed on the same machine, as all Viasfora settings are stored in a single shared file (c:\users\<your user>\Viasfora\Viasfora.xml.


One interesting bit I see is that it appears to be failing on the InitializeTelemetry() method, and in particularly when it calls GetService(), which I think should only happen when it is attempting to load the configuration.

It could be that the config file is invalid, but you could open it and inspect it just in case (feel free to send me a copy if you need me to look at it).

Can you take a look at it and let me know if it seems wrong somehow?

**Comment by MartinL0815** [comment]
Hi Tomasr,

the XML file looks fine and is well formed.
Since there is nothing special about the configuration, I attached the XML file to this comment.

For testing purpose, I moved the file from its location and started VS2015 again … it crashed again.

The Activity log still points to something similar:

> 161  Entering function CVsPackageInfo::HrInstantiatePackage {F419E6BB-F72F-42CF-ACFE-D0D0E17FCB17}  VisualStudio 2016/07/04 15:09:12.895 
> 162  Begin package load [Microsoft.VisualStudio.Shell.VsHubServicePackage] {F419E6BB-F72F-42CF-ACFE-D0D0E17FCB17}  VisualStudio 2016/07/04 15:09:12.895 
> 163 ERROR Still unable to load MEF component DLL: Could not load file or assembly 'Microsoft.CSS.Editor, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
>           C:\windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.VisualStudio.JavaScript.Project\v4.0_14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.JavaScript.Project.dll   Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost 2016/07/04 15:09:15.197 
> 164 ERROR Still unable to load MEF component DLL: Could not load file or assembly 'Microsoft.VisualStudio.Workspaces.Contracts, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
>           C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\DGWQ5VGT.MHG\TMLanguage.dll   Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost 2016/07/04 15:09:21.862 
> 165 ERROR Error loading extension: This VSIX does not apply to any product installed on this machine. The problem could be that the VSIX manifest's format is not recognized, or that the manifest has been corrupted. Data at the root level is invalid. Line 1, position 1. 
>           C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\MICROSOFT\VSGRAPHICS\   Extension Manager 2016/07/04 15:09:36.567 
> 166 ERROR Error loading extension: This VSIX does not apply to any product installed on this machine. The problem could be that the VSIX manifest's format is not recognized, or that the manifest has been corrupted. Data at the root level is invalid. Line 1, position 1. 
>           C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\MICROSOFT\VSGRAPHICS\   Extension Manager 2016/07/04 15:09:38.519 
> 167 ERROR An item with the same key has already been added.   Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost 2016/07/04 15:13:43.885 
> 168 ERROR Still unable to load MEF component DLL: Could not load file or assembly 'Microsoft.CSS.Editor, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
>           C:\windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.VisualStudio.JavaScript.Project\v4.0_14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.JavaScript.Project.dll   Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost 2016/07/04 15:13:54.234 
> 169 ERROR Still unable to load MEF component DLL: Could not load file or assembly 'Microsoft.VisualStudio.Workspaces.Contracts, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
>           C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\DGWQ5VGT.MHG\TMLanguage.dll   Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost 2016/07/04 15:13:54.235 
> 170 ERROR An item with the same key has already been added.   Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost 2016/07/04 15:14:37.870 
> 171 ERROR LegacySitePackage failed for package [Winterdom.Viasfora.VsfPackage, Viasfora, Version=2.5.0.0, Culture=neutral, PublicKeyToken=null]Source: 'mscorlib' Description: Exception has been thrown by the target of an invocation. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: An item with the same key has already been added. at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) at Microsoft.VisualStudio.ExtensibilityHosting.VsExportProviderFactory.<>c__DisplayClass54_0.<CreateAssemblyCatalogsAsync>b__6(KeyValuePair`2 namedCatalog) at System.Threading.Tasks.Dataflow.ActionBlock`1.ProcessMessage(Action`1 action, KeyValuePair`2 messageWithId) at System.Threading.Tasks.Dataflow.ActionBlock`1.<>c__DisplayClass5.<.ctor>b__0(KeyValuePair`2 messageWithId) at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.ExtensibilityHosting.VsExportProviderFactory.<CreateAssemblyCatalogsAsync>d__54.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at Microsoft.VisualStudio.ExtensibilityHosting.VsExportProviderFactory.<GetCurrentAssemblyCatalogsAsync>d__31.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.ExtensibilityHosting.VsExportProviderFactory.<GetExportProviderFactoryAsync>d__23.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.<GetMEFV3ExportProviderInternalAsync>d__49.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.<GetMEFV3ExportProviderWrapperAsync>d__48.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread() at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread() at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions) at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod) at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetLazyValue[T](AsyncLazy`1 lazy) at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]() --- End of inner exception stack trace --- at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at Winterdom.Viasfora.Compatibility.SComponentModel.GetService[T]() at Winterdom.Viasfora.Telemetry.Initialize(DTE2 dte) at Winterdom.Viasfora.VsfPackage.InitializeTelemetry() at Winterdom.Viasfora.VsfPackage.Initialize() at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)System.ArgumentException: An item with the same key has already been added. at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) at Microsoft.VisualStudio.ExtensibilityHosting.VsExportProviderFactory.<>c__DisplayClass54_0.<CreateAssemblyCatalogsAsync>b__6(KeyValuePair`2 namedCatalog) at System.Threading.Tasks.Dataflow.ActionBlock`1.ProcessMessage(Action`1 action, KeyValuePair`2 messageWithId) at System.Threading.Tasks.Dataflow.ActionBlock`1.<>c__DisplayClass5.<.ctor>b__0(KeyValuePair`2 messageWithId) at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.ExtensibilityHosting.VsExportProviderFactory.<CreateAssemblyCatalogsAsync>d__54.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at Microsoft.VisualStudio.ExtensibilityHosting.VsExportProviderFactory.<GetCurrentAssemblyCatalogsAsync>d__31.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.ExtensibilityHosting.VsExportProviderFactory.<GetExportProviderFactoryAsync>d__23.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.<GetMEFV3ExportProviderInternalAsync>d__49.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.<GetMEFV3ExportProviderWrapperAsync>d__48.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread() at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread() at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions) at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod) at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetLazyValue[T](AsyncLazy`1 lazy) at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]() {3338742C-7926-4949-9E57-3FCBB8D0A976} 80131604 VisualStudio 2016/07/04 15:14:40.087 
> 172 ERROR SetSite failed for package [Winterdom.Viasfora.VsfPackage, Viasfora, Version=2.5.0.0, Culture=neutral, PublicKeyToken=null](null) {3338742C-7926-4949-9E57-3FCBB8D0A976} 80131604 VisualStudio 2016/07/04 15:14:40.091 
> 173 ERROR End package load [Winterdom.Viasfora.VsfPackage, Viasfora, Version=2.5.0.0, Culture=neutral, PublicKeyToken=null] {3338742C-7926-4949-9E57-3FCBB8D0A976} 80131604 VisualStudio 2016/07/04 15:14:40.195 

Any idea?

Or - can I deactivate Viasfora without VS2015 UI? I need to continue my work! :(

Cheers,

Martin
[viasfora.txt](https://github.com/tomasr/viasfora/files/346587/viasfora.txt)

**Comment by tomasr** [comment]
You're right; there doesn't seem to be anything invalid in there.

Most of the errors you point out in the log are not related to Viasfora. For example, "Microsoft.VisualStudio.Workspaces.Contracts" is a Roslyn DLL upon which Viasfora does not depend (nor does it use it at all) so I wonder if something else is going on in there.

Try the following:

Option 1: Clean the component cache:
* Close VS
* Delete the ```%USERPROFILE%\AppData\Local\Microsoft\VisualStudio\14.0\ComponentModelCache``` folder
* Start VS

Option 2: Manually delete Viasfora
* Close VS
* Locate your ```%USERPROFILE%\AppData\local\Microsoft\VisualStudio\14.0\Extensions``` folder, then go over each one to see if it contains the Viasfora assemblies.
* Delete the folder found in the last step
* Probably want to reset the component cache again just in case
* Not sure if you'll need to run ```devenv.exe /setup``` just in case.

Let me know if any of that works for you.

**Comment by MartinL0815** [comment]
Hi Tomasr,

thanks for your support - unrelated to Viasfora!
I finally resolved the problem in uninstalling and installing again. :(
At the end ... deleting the folder for the component cache and the extension caches have helped!

Cheers,

Martin
