### ISSUE TITLE
High-Contrast-mode and the brace tool tip colors

### ISSUE THREAD

**Issue by MartinL0815** [tomasr/viasfora#162]
Hi,

I work with high-contrast-mode/theming (need to work with).
VS2015 automatically switches to the high-contrast theme.

Placing the mouse pointer onto a brace, the tool tip looks like this:

> ![brace tool tip](https://cloud.githubusercontent.com/assets/525700/16916782/1059e356-4cff-11e6-98af-2c8406352174.png)

As you can see the tip background color is very near to the text editor background (black).
It is (for me) difficult to differ between the text editor and the tool tip - even if the font size is a bit smaller.
Is there (a future) chance for changing the background? Automatically in relation to the VS theme? Or manually in the "Fonts & Colors" section of the environmental options?
Or should the setting …

> 
![tip highlight setting](https://cloud.githubusercontent.com/assets/525700/16916880/803310da-4cff-11e6-8c7c-6fb260fd100b.png)

… already the one to configure this background color?
If so, this setting does not work in high-contrast-mode.

Cheers,

Martin

**Comment by tomasr** [comment]
That's an interesting feedback; and honestly have never tried the specific scenario.

Couple of things:
* The tip background itself will be the same as the editor window.
* The Tip Highlight option changes the color of the line that contains the matching brace in the tooltip, not the entire tooltip background.
* The overall tip, however, should have a border that's supposed to use the ToolTipBrushKey color in the Visual Studio color scheme, like here:

![image](https://cloud.githubusercontent.com/assets/16179/16936381/cba1352a-4d2b-11e6-8764-956daba43485.png)

It would appear that in this case, that color is the same as the background editor window color, and so it's..... missing :(

I'll try to take a look and see how it could be improved, though will take a few days.

**Comment by MartinL0815** [comment]
Hi Tomas,

I really wonder what's going on, because tool tips ain't cause visual problems.
Their colors, visualization allows to recognize them, distinguish them from eg editor backgrounds.

I'm back in the office tomorrow and will share screenshots and more information.

Have mood day!

Martin Lemburg
Berlin / Germany

martin.lemburg@gmx.net
http://about.me/Martin0815

------- Original message -------

**Comment by MartinL0815** [comment]
Here two screenshots of the "normal" tooltips within VS2013:

- the structure visualizer from the Productivity Power Tools (yes, with wrong colors in high-contrast)
![Productivity Power Tools 2015 tooltip](https://cloud.githubusercontent.com/assets/525700/16981691/fe5fddc2-4e6b-11e6-8442-56ad84e1e4fa.png)
- tooltip from hovering over a method showing its signature
![VS2013 tooltip](https://cloud.githubusercontent.com/assets/525700/16981719/219b59f6-4e6c-11e6-967b-1cca933f65ed.png)

So - your tooltip misses a border/frame (COLOR_WINDOWFRAME).

Cheers,

Martin
