### ISSUE TITLE
In C# code #if and #else highlight but #endif and #elif do not

### ISSUE THREAD

**Issue by richardcox13** [tomasr/viasfora#166]
I assume this is the `if` and `else` are being detected as C# keywords even when the preceding character is `#` (making them pre-processor keywords).

This makes code like this look odd:

![untitled](https://cloud.githubusercontent.com/assets/4578827/17360029/582fba16-5961-11e6-9b9f-e535cd40da75.png)

**Comment by tomasr** [comment]
It's been a bug since Roslyn, but need to sit down and figure it out. I'll try to fix it this weekend or next week that I'll be home.
