### ISSUE TITLE
Keywords

### ISSUE THREAD

**Issue by Schrander** [tomasr/viasfora#167]
Nice extension for a start. 

Is it possible to add custom keyword-collections for any language.  In example a C# coloring for "return, continue, break, yield"

**Comment by tomasr** [comment]
You can customize the list for each language, provided they are taken from words that the underlying language service already classifies as "keywords":
![image](https://cloud.githubusercontent.com/assets/16179/17653853/259a1d90-6261-11e6-9a5b-5a8e6fb54e4a.png)
