### ISSUE TITLE
Custom Configuration File Location

### ISSUE THREAD

**Issue by bing281** [tomasr/viasfora#168]
Can we get the ability to customize the viasfora.xml locaiton the current location it is in causes me some problems with group policies made by my IT department :(

**Comment by tomasr** [comment]
Where would you want to put it? and where should we store the configuration file location? (gotta love the indirection!)

**Comment by tomasr** [comment]
Just implemented a way to support this. Once this version is released, you'll be able to just set the `VIASFORA_SETTINGS` environment key to the full path and file name of the settings file.

For example:
```
VIASFORA_SETTINGS = "C:\settings\Viasfora.xml"
```

It is recommended to close all instances of Visual Studio before setting this environment variable and then launching them again (notice that Viasfora will not copy any existing settings in the default location to the new one).

**Comment by bing281** [comment]
Thanks :)
