### ISSUE TITLE
Is this a bug? The color does not match.

### ISSUE THREAD

**Issue by rosdi** [tomasr/viasfora#176]
Show below a screenshot of my Web.Release.Config
Notice the color for appSettings opening and closing bracket doesn't match? Is this intentional? I am new to viasfora.

![image](https://cloud.githubusercontent.com/assets/5094028/20342177/57b24bce-ac24-11e6-9362-2750e24a687b.png)

**Comment by tomasr** [comment]
Hi @rosdi,

Yes, this is one of Viasfora's feature to make XML/HTML code more readable (one of the features I often miss the most in Vim themes). If you do not like it, you can disable by setting the "Highlight XML closing tags" option in Tools -> Options -> Viasfora -> XML Editor to false:

![image](https://cloud.githubusercontent.com/assets/16179/20345497/6abcf1ec-abc5-11e6-963a-55d8834d557f.png)

**Comment by rosdi** [comment]
Ok... I was expecting it to behave like the colored C# curly braces... but your explanation makes sense... I will leave it as it is... I think I might like it!... thanks.
