### ISSUE TITLE
NullReference Exception - New Version

### ISSUE THREAD

**Issue by modulexcite** [tomasr/viasfora#178]
Thank you for an excellent extension.
I have installed the new version 3.4.124 and Visual Studio is reporting an error upon launch. Below are the details.

### OS Version
Windows 7 SP1

### VS Version
Visual Studio 2015 Professional Update 3

### Error in Activity Log:
> System.NullReferenceException: Object reference not set to an instance of an object. at Winterdom.Viasfora.Text.PresentationMode..ctor(IWpfTextView textView, IPresentationModeState state, IVsfSettings settings) at Winterdom.Viasfora.Text.PresentationModeFactory.<>c__DisplayClass4_0.<TextViewCreated>b__0() at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator) at Winterdom.Viasfora.Text.PresentationModeFactory.TextViewCreated(IWpfTextView textView) at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.<>c__DisplayClass241_0.<BindContentTypeSpecificAssets>b__1() at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)

**Comment by tomasr** [comment]
I've pushed an update. Let me know if it fixes the error for you!
(You might need to delete the VS Component Cache if it's getting stuck).

**Comment by modulexcite** [comment]
it seems like the issue has been resolved in the new version, thanks for fixing it @tomasr.
