### ISSUE TITLE
VS 2017 with Resharper causing crashes

### ISSUE THREAD

**Issue by vincentw56** [tomasr/viasfora#182]
I seem to having an issue with VS 2017 and it crashing with this extension and Resharper both enabled. If I disable this extension or Resharper, everything works fine. But with both enabled, I get constant crashes. It is pretty frequent.

**Comment by tomasr** [comment]
* What VS2017 version are you using? RC3?
* What resharper version?

Anything you can tell me about *when* the crashes happen? (i.e. any specific action that triggers it more often than not?)

**Comment by vincentw56** [comment]
Microsoft Visual Studio Enterprise 2017 RC Version 15.0.26127.3
JetBrains ReSharper Ultimate 2016.3.2    Build 107.0.20170126.120331

There isn't really one thing or the other. The project I am working on right now has a lot of Typescript in it and that is were I am working mostly.

I notice it more when I am typing in the TS files. But sometimes, I won't be doing anything and VS will be running in the background and I will get notified it crashed. I can work for two hours just fine. Or I can work for 5 minutes and it crashes.

The last update with VS caused an issue so I had to uninstall and reinstall it. What I did was install Resharper and work with it for a day just that way. Once I knew it was running smoothly, I started adding in a few extensions I needed. I ran it that way for another day with no issues. So I installed Viasfora, and it crashed with in about 10 minutes of working. I disabled it, and have been working fine for the last 3 or so hours.

**Comment by tomasr** [comment]
When the crash happens, are you seeing any .NET Runtime errors in the Application Event Log on your machine? Or maybe checking the ActivityLog.xml file just in case there's anything in there that can be useful?

I suspect it might be an issue with TS even if not related to Resharper..... The JavaScript/TypeScript editor changed how some things are returned and I suspect that might have something to do with it, so knowing you're working with TypeScript is definitely useful information, thanks!

**Comment by tomasr** [comment]
Oh, forgot to ask.... what version of Viasfora are you using? The one on the VS marketplace, or the dev builds published in http://vsixgallery.com/ ?

**Comment by vincentw56** [comment]
I am using the one published on VS Marketplace.

**Comment by tomasr** [comment]
Can you try the one in vsixgallery or https://ci.appveyor.com/project/tomasr/viasfora/build/artifacts instead? There was a change in there specifically done to try fixing a bug in ts/js parsing, and wondering if that makes any difference.

**Comment by vincentw56** [comment]
Sure, I will give it a try and let you know.

**Comment by vincentw56** [comment]
So far so good, I will keep using it over the next few days and let you know.

**Comment by vincentw56** [comment]
Well, it is still crashing every so often. No reason for it. It crashed while editing some .cs files in a project with no Typescript. It crashed while editing a .js file in my project with Typescript. Sometimes it will work for a few hours. Sometimes it will crash within minutes.

**Comment by tomasr** [comment]
I've been trying to repro this, but so far, it has not crashed. Will keep trying to see if I can figure out what's going on.

**Comment by vincentw56** [comment]
I am not sure if this is completely related to Viasfora and Resharper. I think it could be that VS 2017 is just unstable. I've had it crash twice today without Viasfora activated. Of course, when I do activate it, it crashes more often.

**Comment by vincentw56** [comment]
I am closing this as this crashing doesn't seem to be related to Viasfora. I had disabled and still had the crashes. Using the RTM version with Viasfora enabled and it seems to be better. But even if it still crashes, I doubt this was related.
