### ISSUE TITLE
Updated to v3.4.128, now getting this error

### ISSUE THREAD

**Issue by fdncred** [tomasr/viasfora#185]
This is an excerpt of ActivityLog.xml.  Unfortunately I've had to disable ViasFora. :(

Any ideas how to fix it?  All I was doing when this error popped up was adding a using statement like:
using MahApps.Metro.Controls and when i went to put the semicolon, it blew up.  I restarted VS2015 and put the semicolon and it blew up again with an exception that pointed me to the ActivityLog.

System.InvalidOperationException: Cannot Match. The session is dismissed. at     Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Match() at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Start() at Winterdom.**Viasfora**.Intellisense.PlainTextCompletionCommandHandler.TriggerCompletion() at Winterdom.**Viasfora**.Intellisense.PlainTextCompletionCommandHandler.StartSession(Boolean byCommand) at Winterdom.**Viasfora**.Intellisense.PlainTextCompletionCommandHandler.HandleChar(Char typedChar) at Winterdom.**Viasfora**.Intellisense.PlainTextCompletionCommandHandler.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at NoahRichards.AlignAssignments.CommandFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Text.Formatting.Implementation.CommandFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.PeekF1.CommandFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at CMcG.CodeAlignment.CommandFilter.Exec(Guid& cmdGroup, UInt32 cmdId, UInt32 options, IntPtr inArg, IntPtr outArg) at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam) at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args) at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c.<DispatchTextInputEvents>b__6_0(KeyProcessor p, TextCompositionEventArgs args) at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass10_1`1.<Dispatch>b__0() at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)   Editor or Editor Extension 2017/03/07 14:53:19.666

**Comment by tomasr** [comment]
Thanks for the report; I don't see the update having much to do with it, as that specific code has not been touched in a long time. So this is blowing up when editing C# files, when adding using statements?

I tried to repro, but was unable to, I will keep trying though, but suspect this would be an older, latent bug, rather than something new.

Question, though: do you have the "Complete During Typing" option in Tools -> Options -> Viasfora -> Intellisense enabled? If so, does it go away if you disable it?

**Comment by fdncred** [comment]
Yes, C#. Yes, I have Complete During Type = True and Handle Complete Word = True. I turned them both to false, but left Enable Plain-Text Completion = True.

I haven't reproduced the problem since turning those both to False. I'll keep working with it and report back if it blows up again.

**Comment by tomasr** [comment]
Awesome, I will try to repro it later, and fix it. I'm also seriously considering removing the functionality, as it is not widely used (and frankly, VsVim has a much better one), so that might be a better option :smile:
