### ISSUE TITLE
Remove Current Line Highlight

### ISSUE THREAD

**Issue by tomasr** [tomasr/viasfora#187]
This feature was only needed on VS2010, which is no longer supported; so the code can now be removed.

**Comment by TheDark** [comment]
This feature allowed the line highlight to remain visible even when the editor was not active (think XAML designer). I used it instead of the VS highlighter because of that. Can in be reenabled, please?

**Comment by tomasr** [comment]
@TheDark I'll consider this, though the best option would really be to submit this to the Visual Studio team so that they can add that to the built-in one :smile: You could do this in their Uservoice forum: https://visualstudio.uservoice.com/forums/121579-visual-studio-ide

**Comment by TheDark** [comment]
Thank you, I'll do that 😄 Even though I don't think they'll pay me any attention... 😞

**Comment by tomasr** [comment]
I'm bringing this back for v3.6, if you're still interested.

**Comment by TheDark** [comment]
@tomasr I definitely am! Thank you so much!
