### ISSUE TITLE
Allow CTRL key to highlight while rainbow braces are disabled.

### ISSUE THREAD

**Issue by Nidre** [tomasr/viasfora#189]
This is not a bug but a feature request.

Not sure if it is already available, but I couldn't figure out. 

I really like the feature that highlight current scope when CTRL key is held down. But rainbow braces are way too tiring for my eyes and way too much information than I need.. I was looking for a way to disable rainbow braces at least until I hold down the CTRL key.

It would incredibly increase this addons usability for me.

**Comment by Nidre** [comment]
Found out I can achieve similar results by using below settings. But would great to have a toggle to enable disable rainbow braces separately from CTRL to highlight feature.

![image](https://cloud.githubusercontent.com/assets/6220948/24393819/ea0b52fe-1399-11e7-8fba-3e654a42b5c7.png)

**Comment by tomasr** [comment]
I've implemented a new option here. To accomplish what you want (I believe) do this:
* Set `Enable Rainbow Tags = True` 
* Set `Rainbow Colorize Braces = False`

Can you give a try to the latest dev build and let me know how that works for you?
