### ISSUE TITLE
Ability to Export/Import Settings

### ISSUE THREAD

**Issue by Nidre** [tomasr/viasfora#199]
I'm using Viasfora on 2 different devices. I've a custom color scheme set up for Viasfora. It would be nice to have a way to export my Viasfora settings and import on my other machine.

**Comment by tomasr** [comment]
Working on this, but ended up on a full-blown refactor of my settings handling code, so will take longer than I expected. It will get done, though.

**Comment by tomasr** [comment]
@Nidre BTW, are you interested in full export/import for all settings including colors, or just colors?

Something I've been thinking about is being able to create/apply color themes (at least for rainbow, but not sure why it couldn't support the rest of the colors in Viasfora), so maybe that would be a better choice if you're interested just in colors.

**Comment by Nidre** [comment]
I would be happy with just themes/skins. But full export/import would be much nicer I guess :)
