### ISSUE TITLE
Any change to port this extension to Jetbrains IDE's?

### ISSUE THREAD

**Issue by iamfreee** [tomasr/viasfora#202]
Hi,

I like this extension very much but i also use Jetbrains IDE's a lot, what are the changes of porting this extension? 😄 

Thanks!

**Comment by tomasr** [comment]
Which specifically are you referring to? IntellyJ? Rider?

To be honest, I have no idea what extensibility model any of them might have, and don't own a license to them, so changes are a bit on the slim-to-none category at the moment ....

**Comment by iamfreee** [comment]
Plugins can support the entire IntelliJ Platform like IntelliJ, Rider, Phpstorm, Webstorm etc..

I have just found one similar plugin:
https://github.com/zjhmale/intellij-rainbow
But viasfora colors are prettier.

Thanks!

**Comment by tomasr** [comment]
Sounds like a better option would be to ask the author of that extension for alternative colors, maybe? :smile:
