### ISSUE TITLE
JavaScript Template Literals Support

### ISSUE THREAD

**Issue by jasonwoods-7** [tomasr/viasfora#203]
When using Rainbow Braces & JavaScript Template Literals, the string parsing doesn't seem like it's working correctly.  On the fourth line in my screen shot below, before the template literal, the color of the paren is blue, but the ending paren is white.  The next opening paren is red instead of grey.

![image](https://user-images.githubusercontent.com/1322531/27544994-4c08f758-5a54-11e7-846f-3c04f09d3674.png)

**Comment by tomasr** [comment]
Thanks for reporting, This will likely require some work similar to how C# string interpolation is being handled.

Adding reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
