### ISSUE TITLE
Support color themes

### ISSUE THREAD

**Issue by tomasr** [tomasr/viasfora#207]
Support color themes:

- Ship at least one theme as a json file included in the distro
- Support themes in the %profile%\Viasfora folder
- Provide a way to apply an existing theme
- Provide an option to export existing settings into a new theme file

**Comment by tomasr** [comment]
Initial support for themes is done.

No support is yet added for a theme list or something like that.

**Comment by tomasr** [comment]
Also, to do:
* Allow you to specify the background color in an explicit fashion by converting `'default'` to `Transparent`, rather than simply ignoring it (and write both fg and bg for each classification when exporting theme)

**Comment by CADbloke** [comment]
+1 for automatic background. Presently my code looks like it has lots of little black holes in it. Kinda fitting really but that's a whole different story.

**Comment by tomasr** [comment]
@CADbloke That part is already supported. However, I probably screwed up converting your theme (I think my script isn't handling all color specifications correctly)

**Comment by tomasr** [comment]
Initial version is now done and released in v3.6
