### ISSUE TITLE
Advanced customization of keywords/braces

### ISSUE THREAD

**Issue by 0x63dev** [tomasr/viasfora#210]
Instead of just being able to select color of things, be able to select other text decorations, such as

- bold text

- size of text

- shadow/glow

- italic/underline

- different font

**Comment by tomasr** [comment]
Bold and size of text you can already select from the Fonts / Options dialog. The existing support for italics is a bit of a hack, as this is not supported by the Visual Studio mechanism used to store font/color information unfortunately.

Is there any specific scenario you're looking at?

**Comment by 0x63dev** [comment]
Some colors of braces are hard to notice at first look, making specific level of braces bold/italic/bigger than other would make it a lot easier. ex,level 2 => bold, level 3 => italic . And also knowing that your braces are bold makes it very easy to get a grasp of code size/block

**Comment by tomasr** [comment]
You can already do mixed bold/non-bold braces using the Fonts & Colors dialog or themes.

Italics, unfortunately, no good way to do.
