### ISSUE TITLE
v 3.5.146 breaks colors

### ISSUE THREAD

**Issue by CADbloke** [tomasr/viasfora#211]
Greetings

Firstly, thanks - this is a great extension.

Updating from v 3.5.139 to 3.5.146 on the gallery nightlies breaks all the colors - they go back to defaults and ignore the settings in Visual Studio's Font options. Observed on 2x VS2015 & a VS2017 installation.

Uninstalling and then installing the release version from the marketplace fixes it.

cheers

**Comment by tomasr** [comment]
@CADbloke That's actually expected, as I had to rename the classifications to make them uniform for the new themes feature. However, I can help you solve that relatively easy.... can you export your Fonts & Colors section from Visual Studio (to a .vssettings file) and send it over email? I'll get you a matching theme you can import with the new feature :smile:

**Comment by tomasr** [comment]
[Here](https://gist.github.com/tomasr/e7c2cc99eded6f970ec4f4c9d7a64b43) is an initial attempt at a PowerShell script to extract the old color items into a new Viasfora Theme in JSON format.

And [here](https://gist.github.com/tomasr/72114f117d3c327edbc008d9f8f9387b) is what the script generates. Give it a try and let me know if that matches your old styles :smile:

**Comment by CADbloke** [comment]
Yup. Win! All looks good. You need to change the file suffix so the importer file dialogue in VS settings finds the file.
