### ISSUE TITLE
Viasfora on VS 2017 for Mac

### ISSUE THREAD

**Issue by Pgaudreau** [tomasr/viasfora#212]
Hi,
I was wondering if viasfora will eventually be compatible with the new Visual Studio that came out on Mac (VS 2017)? 
Since it it a .vsix, it can't be installed. I think it has to be a .mpack format.
Or what could be a way to do it manually?

**Comment by tomasr** [comment]
Right now, I don't think that would work. As far as I know, VS for Mac uses an entirely different extensibility and editor model (based on the Monodevelop code). I do not know if there are any plans to unify them and bring them closer, but even then it would certainly require significant changes.

Unfortunately, I don't own a Mac machine I can use, so I haven't even used VS for Mac yet. I'll keep an eye out for any info on how the extensibility model works, though.

**Comment by Pgaudreau** [comment]
Excellent, thank you for the answer!
