### ISSUE TITLE
Updating to v3.6 erases all your color setting

### ISSUE THREAD

**Issue by EliiseS** [tomasr/viasfora#213]
With an added bonus of not being able to reimport the setting via the Visual studio importer(I had previously saved my color setting to a visual studio import file), because that is no longer used. 

Also unable to revert to previous version. 

I've fixed this by going to a not updated computer and taking pictures of my color settings. (This is also how I found out the settings are wiped, because I then also updated to the latest version)

**Comment by tomasr** [comment]
See [this for information](http://winterdom.com/2017/08/02/viasfora-theme-conversion.html) on how to migrate your settings.
