### ISSUE TITLE
Won't respect color changes

### ISSUE THREAD

**Issue by fdncred** [tomasr/viasfora#214]
It's nice to customize the colors via Tools->Options->General->Flow Control Keywords.

It would be even nicer if it remembered those changes.

I'm not sure what the order of operations is that allow my customizations to be overwritten but I do know that I have to reset them about once a day. I've also had Viasfora's config panel crash VS2017.

I'm running Viasfora v3.6.147
Visual Studio 2017 15.2 (26430.16)
Windows 10 Creators Update

**Comment by tomasr** [comment]
Color customization should stick. However, a common source of those getting missed is editing settings while multiple Visual Studio versions are opened (in that case, the last one to close will overwrite any VS settings; if that is not the one you did any customization, then you'll loose them for sure). That's not a Viasfora thing, that's just VS being VS :smile:

If that is not your case, we can try to troubleshoot deeper, but color settings are all saved in the VS Fonts & Colors options, so not much I control in there.

That said, Viasfora 3.6 did have a breaking change with regards to color customization; see http://winterdom.com/2017/08/02/viasfora-theme-conversion.html

If you've seen any crashes here, recently, please share any errors in your Visual Studio ActivityLog.xml file, or better yet, capture a dump of the crash and I'd be happy to take a look and fix any issues. Can you share any info on what you were doing when it crashed?

**Comment by fdncred** [comment]
@tomasr This was in my Diagnostic Log. My activity log has already been overwritten. One thing is for sure, before it crashed I couldn't get anything to appear in the Tools->Options->Viasfora menu. It wouldn't load it at all. I closed the options dialog and opened it again and things were there but none of the setting were filled in and all the colors were white.

```
UNHANDLED EXCEPTIONS FROM PROCESS 59920:
=====================
8/7/2017 1:26:53 PM
System.Runtime.InteropServices.COMException (0x80040152): Could not find the key in the registry (Exception from HRESULT: 0x80040152 (REGDB_E_KEYMISSING))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Winterdom.Viasfora.Options.ClassificationColors.Load(ColorStorage colorStorage)
   at Winterdom.Viasfora.Options.ClassificationList.Load(String[] classificationNames)
   at Winterdom.Viasfora.Options.GeneralOptionsPage.LoadSettingsFromStorage()
   at Microsoft.VisualStudio.Shell.DialogPage.OnClosed(EventArgs e)
   at Microsoft.VisualStudio.Shell.DialogPage.DialogSubclass.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
===================
```
I frequently have two VS2017 windows open but I set them both to have the same colors. I'm not sure how one would overwrite the other and somehow restore the default colors but maybe that is happening somehow.

**Comment by fdncred** [comment]
What it the process to make the colors stick? I reboot and bring VS2017 up this morning and the colors are reset again. I upgrade to 15.3, the colors are reset. I run two VS2017's the colors reset. Sometimes they'll last a day or two but they reset eventually.

**Comment by tomasr** [comment]
There's no process; Viasfora has nothing to do with it at all. You wouldn't happen to have the "Synchronize Settings" option in Visual Studio enabled, by any chance, would you?

**Comment by fdncred** [comment]
I do have Sync Settings enabled. I run VS2017 on 3 PCs. 2 of them have Viasfora installed and have the same settings. One doesn't have Viasfora installed at all.

**Comment by tomasr** [comment]
If all of them are tied to the same account, I wonder if perhaps the third instance without Viasfora at all is deleting the entries in Fonts & Colors for Viasfora and causing them to be reset to the default color.... What happens if you disable sync settings on the instance without Viasfora? Does it keep happening?

**Comment by fdncred** [comment]
I'll try it and see what happens.
