### ISSUE TITLE
[Feature Suggestion] Highlight invalid escape sequences

### ISSUE THREAD

**Issue by marklam** [tomasr/viasfora#219]
The escape sequence highlighting used to show all backslash combinations in strings, but now only highlights valid combinations.

One nice feature of the previous approach was that if I forgot to @-quote a path string, it would be filled with escape highlights, so I'd notice my mistake (when it highlighted \P in "c:\Program files", or \T in "d:\Temp")

If there was a highlight option/colour for bad escape sequences, then it would be useful for spotting both errors within the string, and paths that haven't been @-quoted.

**Comment by tomasr** [comment]
Are you referring to C# specifically? or some other language?

**Comment by marklam** [comment]
Oops, that would have been useful information to include :-)
It was specifically in F# scripts, .fsx files.

**Comment by tomasr** [comment]
Would something like this work?

![image](https://user-images.githubusercontent.com/16179/32528285-3103af8c-c400-11e7-9604-222dd7311fd1.png)

Introduces a new classification for invalid escape sequences.....

**Comment by marklam** [comment]
Yes, that looks like it would alert me to the fact I'd missed the string-escape, and it's looks helpful for its intended purpose too! :-)

**Comment by marklam** [comment]
Works well, thanks!
