### ISSUE TITLE
Unhandled Extension Error

### ISSUE THREAD

**Issue by grabalon** [tomasr/viasfora#221]
We've caught the following exception within VS and it looks like something related to this extension. Here's the exception information:
Exception Type: System.InvalidOperationException
Callstack: 
GetCurFile returned 0x80004001
Winterdom.Viasfora.TextEditor.CheckError(Int32 hr, String operation)
Winterdom.Viasfora.TextEditor.GetFileName(ITextBuffer buffer)
Winterdom.Viasfora.Outlining.UserOutliningManager.LoadRegions(ITextBuffer buffer)
Winterdom.Viasfora.Outlining.UserOutliningManager.<>c__DisplayClass1_0.<Get>b__0()
Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)
Winterdom.Viasfora.Outlining.UserOutliningManager.Get(ITextBuffer buffer)
Winterdom.Viasfora.Outlining.UserOutliningTaggerProvider.CreateTagger[T](ITextBuffer buffer)
Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)

**Comment by tomasr** [comment]
What version of Viasfora are you using? Because this seems like the same issue as #216, which was fixed a while ago.

**Comment by grabalon** [comment]
Oh, yep, looks the same sorry. We caught it with a different method and I opened this issue without looking too deeply. Our data came from telemetry which didn't have your extension version in it. I'm comfortable closing this.
