### ISSUE TITLE
[Feature Request] Ability to disable "Visibility Keywords" color.

### ISSUE THREAD

**Issue by gluons** [tomasr/viasfora#222]
I personally don't want **Visibility Keywords** color change.  
It should be great if you give my an option to disable it. 😄

**Comment by tomasr** [comment]
There is no way right now to just turn off one kind of keyword. However, you could just customize the configuration for your language of choice by deleting all default keywords in the visibility category.

Does that work for you?

**Comment by gluons** [comment]
After I installed **Viasfora**, all my visibility keywords (e.g. `public`, `private`) turn in to gray. And I see **Visibility Keywords** option in **Viasfora** settings, so I try to request this feature.

Did you mean customize it in **Fonts and Colors** setting that I may be able to revert my keywords, right?

**Comment by tomasr** [comment]
Thought I had answered this, but apparently dreamed it. Sorry about that!
Adding now an option in the Viasfora -> General page for this:

![image](https://user-images.githubusercontent.com/16179/33972614-afaa081e-e04c-11e7-83e3-2c2012eb00f5.png)

**Comment by gluons** [comment]
Perfect! Thank you very much.

![Great](https://media.giphy.com/media/xHMIDAy1qkzNS/giphy.gif)
