### ISSUE TITLE
Customize key binding for Rainbow Highlighting (Request)

### ISSUE THREAD

**Issue by Grifplex** [tomasr/viasfora#226]
First off, Beautiful extension!

Will you add the ability to customize the Rainbow Highlighting key binding?
Will you add an option to toggle Rainbow Highlighting?

**Comment by tomasr** [comment]
> First off, Beautiful extension!

Thanks for the kind words!

> Will you add the ability to customize the Rainbow Highlighting key binding?

What do you mean by this? To which key binding are you referring to?

**Comment by Grifplex** [comment]
To be able to change the Rainbow Highlighting trigger key from Left Control to another key.

**Comment by tomasr** [comment]
What other key would you want to use to trigger it? It would need to be a modifier key that doesn't trigger any other behavior, so something like `Alt` will not work. Right `Ctrl` maybe?

**Comment by Grifplex** [comment]
I find it too easy to trigger on the Left `Ctrl` when I copy and paste. It is handy, just a bit annoying when unintentionally triggered.
Right `Ctrl` would be better for me. :)

**Comment by tomasr** [comment]
Added an option for this. You should be able to test it on the latest [dev build](https://ci.appveyor.com/project/tomasr/viasfora), but it should go out into the next public release.
