### ISSUE TITLE
Rainbow braces not working with C++ number separator

### ISSUE THREAD

**Issue by xyznobody2** [tomasr/viasfora#230]
In C++, rainbow braces fail to find the matching closing parenthesis when an odd number of number separators is used within the parentheses:
```C++
{
    int x;
    if ((x & 0xFFFF'0000) != 0) // <- these last 2 ) are not colored
        ;
} // <- this is highlighted as an unmatched brace
```

**Comment by xyznobody2** [comment]
I think that the number separator is interpreted as a character literal start that is not ended and so expands to the end of the line.

**Comment by tomasr** [comment]
Thanks for reporting! I had added support for number separators, but completely forgot to add them to hex literals ¯\_(ツ)_/¯.

Should be fixed in the latest dev build now.
