### ISSUE TITLE
VS throws error Winterdom.Viasfora.Xml.XmlTagger (System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values)

### ISSUE THREAD

**Issue by nimeshdhruve** [tomasr/viasfora#239]
Thanks for such a helpful extension. This extension is one of my favorite extension but lately I am noticing one weird error and I thought I would pass the details to you.

When I open file _ValidationScriptsPartial.cshtml Visual studio consistently throws en error as shown in the below screen shot.

![vserror](https://user-images.githubusercontent.com/7783989/40114302-5dc31bc4-58da-11e8-8d1f-85f36c15262b.png)

Below is the excerpt from the ActivityLog.xml and I am guessing that this error is because of Viasfora extension as after disabling the extension this error doesn't occur when I open the file again. But this is such a useful extension that I don't want to disable it. So thought I will pass this information to you and see if you can reproduce the issue.

	<entry>
		<record>964</record>
		<time>2018/05/16 11:16:48.455</time>
		<type>Error</type>
		<source>Editor or Editor Extension</source>
		<description>System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.&#x000D;&#x000A;Parameter name: start&#x000D;&#x000A;	
			at Microsoft.VisualStudio.Text.Span..ctor(Int32 start, Int32 length)&#x000D;&#x000A;	
			at Winterdom.Viasfora.Xml.XmlTagger.&lt;DoXAMLorHTML&gt;d__18.MoveNext()&#x000D;&#x000A;	
			at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__39.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;	
			at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
	</entry>

To troubleshoot the issue I disabled XML Editor highlighting (and restarted VS) but the error still remains.

![xmlhighlightdisabled](https://user-images.githubusercontent.com/7783989/40114425-e1c5ccaa-58da-11e8-8360-eca39a854534.png)

OS: Windows 10 Pro
Visual Studio: Visual Studio 2017 Pro, Version: 15.7.1
Project: Asp.Net Core 2.1

Please feel free to let me know if you need more details or if you think this is not because of Viasfora and thanks again for this wonderful extension.

**Comment by tomasr** [comment]
@nimeshdhruve thanks for reporting! Love that you provided such good details; I'll be sure to track this down and fix it!
