### ISSUE TITLE
New Feature: Rainbow Lines

### ISSUE THREAD

**Issue by tomasr** [tomasr/viasfora#240]
Add dynamic highlighting of the closest enclosing brace pair (a la Rainbow Highlight) using a line that connects the opening and closing braces.

**Comment by tomasr** [comment]
Initial implementation:
![rainbow-lines](https://user-images.githubusercontent.com/16179/40257544-ce7828d0-5aee-11e8-9ee4-5cda7b9c2fde.gif)

**Comment by giggio** [comment]
I like it!

**Comment by tomasr** [comment]
Releasing in v4.0 as is, and will continue to improve in future versions. Once performance has been more optimized, I'll consider enabling it by default.
