### ISSUE TITLE
Error parsing string

### ISSUE THREAD

**Issue by giggio** [tomasr/viasfora#242]
If you open this file on VS with Viasfora enabled it will parse the string that starts on line 13 incorrectly:

https://github.com/code-cracker/code-cracker/blob/master/test/CSharp/CodeCracker.Test/Style/TaskNameASyncTests.cs

It seems that the curly braces confuse the parser. Here is an image:

![incorrectly parsed string in vs](https://user-images.githubusercontent.com/334958/40274221-a908528c-5ba7-11e8-916f-9e600a57ae01.png)

**Comment by tomasr** [comment]
Thanks for reporting! The confusion seems to come from the format string parsing code. I'll fix it!
