### ISSUE TITLE
Support changing width of rainbow lines

### ISSUE THREAD

**Issue by Freyaday** [tomasr/viasfora#248]
The current (4.0) width of rainbow lines can end up thicker than many of the other elements onscreen (other text guides, font features), calling too much attention to itself--especially noticeable due to it typically being colored differently than the surrounding text. 
![image](https://user-images.githubusercontent.com/4823271/40763702-993e0c6e-645a-11e8-8018-13cefabed73a.png)

**Comment by tomasr** [comment]
This is not configurable, but for v4.1 I've reduced the width slightly (see commit https://github.com/tomasr/viasfora/commit/7bf5b344b41b07aa3845fc5bf4ed4ff56bc69328).

Let me know if that works better for you.

**Comment by Freyaday** [comment]
Looks better!

**Comment by neurotech** [comment]
Is there any chance of making this a configurable option?

**Comment by tomasr** [comment]
Not at this moment.... is this something you would want?

**Comment by neurotech** [comment]
Definitely. Very much :)
