### ISSUE TITLE
Align rainbow lines to pixel grid

### ISSUE THREAD

**Issue by Freyaday** [tomasr/viasfora#249]
On 4.0, rainbow lines are not aligned to the pixel grid. This can result in them, especially at small sizes, looking fuzzy and having inconsistent width.
![image](https://user-images.githubusercontent.com/4823271/40763749-d7331f82-645a-11e8-8031-19d766d3343c.png)

**Comment by tomasr** [comment]
I'm not entirely sure what you mean here.... can you clarify?

**Comment by Freyaday** [comment]
![image](https://user-images.githubusercontent.com/4823271/40805671-e183d4bc-64d3-11e8-90b4-0708c3bb2fd4.png)

**Comment by tomasr** [comment]
I have made some changes which are available now in the Dev builds. Can you check if this works better for you? Build available here: https://ci.appveyor.com/project/tomasr/viasfora/build/artifacts

**Comment by Freyaday** [comment]
Latest build has significantly more consistent visual line widths!
![image](https://user-images.githubusercontent.com/4823271/40885481-a5c95078-66db-11e8-9089-efb8da86fd2f.png)
It's not aligned to hard pixel edges, but I get the impression that's not how VS's rendering engine works anyway. But it looks much better now!

**Comment by tomasr** [comment]
Awesome, thanks for confirming!
