### ISSUE TITLE
ItalicsFormatter.FixItalics triggers itself leading to severe performance degradation

### ISSUE THREAD

**Issue by sharwell** [tomasr/viasfora#252]
The following call sequence was revealed during an analysis of a performance feedback report for Visual Studio:

* `ItalicsFormatter.FixItalics` calls &rarr;
* `EndBatchUpdate` calls &rarr;
* `RaiseChangedEvent` calls &rarr;
* `ClassificationFormatMapChanged` calls &rarr;
* `ItalicsFormatter.OnMappingChanged` calls &rarr;
* 💥 `ItalicsFormatter.FixItalics`

:link: Originally reported here:
https://developercommunity.visualstudio.com/content/problem/292162/navigate-to-definition-f12-freezes-visual-studio-w.html

**Comment by tomasr** [comment]
I've been trying to reproduce this for a while without luck. And I *always* run Viasfora with that option enabled, so curious how it came about.

I can only presume it's a race condition where the event fires just after I leave the guard, but don't see how I could possibly detect that. Guess I could setup a delay and only drop the guard after the timer expires....

**Comment by sharwell** [comment]
This user had the Source Overview margin enabled (Tools &rarr; Options &rarr; Text Editor &rarr; All Languages &rarr; Scroll Bars &rarr; Source overview). Other than that, my recommendation would be detecting reentrancy in this method and/or ensuring that it doesn't attempt to set a formatting setting to the same value it already had.

**Comment by tomasr** [comment]
Well, it does have a guard to avoid re-entrancy: https://github.com/tomasr/viasfora/blob/master/src/Viasfora.Core/Text/KeywordTaggerProvider.cs#L85

```C#
      if ( this.working || this.formatMap.IsInBatchUpdate ) {
        return;
      }
```

But I'll see how it can be improved, have some ideas for that.

As I say, I run the exact same setup as the user (always have that source overview thing as well), and have never run into the issue, so must be some weird timing that only kicks up in very specific scenarios.

**Comment by sharwell** [comment]
> this.formatMap.IsInBatchUpdate

Note that the offending stack occurs when leaving the batch update region.

**Comment by tomasr** [comment]
I've done a couple of changes to try to fix it and pushed an update to the marketplace, but have no way to verify it fully fixes the issue (suspect something minor changed in 15.8.x that triggers the issue).

Hopefully it resolves it correctly. I will leave the issue open for now just in case it comes back up.
