### ISSUE TITLE
Brighten all text slightly? Would like more contrast on dark theme

### ISSUE THREAD

**Issue by mejobloggs** [tomasr/viasfora#253]
Hi Tomas,

Thank you for Viasfora, it's very nice. This isn't a bug, but I'm hoping you can help me.

Is there a way to brighten/lighten all text by 10% (just a little)?
Without having to go through each color and making each individual one brighter

I'm using dark theme Visual Studio 2017 and slightly struggling to read default Viasfora colours, as I'm for me, there is not enough contrast between the text and the background.

Thanks :)

**Comment by mejobloggs** [comment]
Nevermind, I just made the default background color a bit darker and that helps. Should think before I speak :)

**Comment by tomasr** [comment]
Well, using [themes](https://github.com/tomasr/viasfora/wiki/Themes) is a very easy way of doing what you want.

Here's what the [default theme](https://github.com/tomasr/viasfora/blob/master/themes/default.json) looks like.

**Comment by mejobloggs** [comment]
Ah that's really cool, didn't know that was possible. Thanks very much!
