### ISSUE TITLE
This extension causes c++ keywords (namely flow control) colour to be bypassed by the editor.

### ISSUE THREAD

**Issue by bretzel** [tomasr/viasfora#254]
Visual Studio 2017 15.7.5

"return; if/else; break; switch/case; while/do; for; (sorry if I miss the rest of the keywords)"

In dark theme, they are displayed in ugly red!!

I can assure that it is this extension because I`ve deactivated extensions one-by-one then restarted VS 2017 for each. When the turn was on "viasfora", once restarted, syntax colors is now as specified in the editor font and colors tools dialogue. 

I LOVE this extension. But I just cannot use it when it corrupts the editor.

**Comment by tomasr** [comment]
Yes, Viasfora does this, it's one of the [features](https://github.com/tomasr/viasfora/wiki/Control-Flow-Keywords), clearly documented.

You can change the default color to whatever you prefer, or disable the feature from Tools -> Options -> Viasfora.

**Comment by bretzel** [comment]
I am guilty. Thanks for your very quick reply.  (Tools->Viasfora). 
Shame on me.
