### ISSUE TITLE
String interpolation bug

### ISSUE THREAD

**Issue by theplasmastorm** [tomasr/viasfora#259]
Viasfora doesn't like to color the curly braces inside nested string interpolation.
Convoluted example:
```
string a = "a";
string b = "b";
string c = "c";
string s = $"{(string.IsNullOrWhiteSpace(a) ? $"{b}" : $"{c}")}";
```
![image](https://user-images.githubusercontent.com/6679183/46164847-ec6d8d00-c243-11e8-8991-d7b56ecedcd2.png)

Viasfora also doesn't like string literals inside string interpolation.
A broken example:
```
string a = "a";
string b = "b";
string s = $"{(string.IsNullOrWhiteSpace(a) ? @"\" : $"{b}")}";
```
![image](https://user-images.githubusercontent.com/6679183/46164976-3e161780-c244-11e8-8339-88a3fa83ea25.png)

Using Dev15.8.5
Viasfora 4.1.182

**Comment by tomasr** [comment]
Yes, this is never going to work properly. My current implementation is a bit of a hack. The problem is that it's impossible to handle all cases using just lexical analysis, and handling nested strings requires way too much state to track what's going on....
