### ISSUE TITLE
Ctrl-click navigation broken

### ISSUE THREAD

**Issue by rickythefox** [tomasr/viasfora#261]
Since installing Viasfora the ctrl-click navigation in code is broken. Disasbling Viasfora fixes this.
![image](https://user-images.githubusercontent.com/1675955/46874362-fa580c00-ce06-11e8-95e1-d9822099b79e.png)

**Comment by tomasr** [comment]
What was the issue?

**Comment by rickythefox** [comment]
@tomasr trying to figure out if it's Viasfora or something else, that's why I closed this. Is it **possible** that this extension is somehow preventing this from working?

**Comment by tomasr** [comment]
I just did a quick test, and seems to be working just fine for me.

I'd be very surprised if Viasfora was somehow involved, but if you can determine that or find a repro, I'd be happy to take a look.

**Comment by rickythefox** [comment]
@tomasr thanks, I'll keep this closed until I figure out what's to blame. Was a bit too quick to file an issue.

**Comment by rickythefox** [comment]
The culpit was VsVim from http://vsixgallery.com
