### ISSUE TITLE
Unresponsiveness on VS 2019 Preview 2.2

### ISSUE THREAD

**Issue by giggio** [tomasr/viasfora#265]
VS is reporting this every now and then.
Right now what happened to me was that I used the VS refactoring to move a class to another file, then I used <kbd>CTRL</kbd>+<kbd>T</kbd> to find it, and then opened it. Then it took about 10 seconds to open.

I am not sure if this is 2019 only. I've been using it exclusively for about a week, and I don't remember the problem on 2017.

If there is any log I can collect for you I'd be happy to.

![image](https://user-images.githubusercontent.com/334958/52420879-0cf30100-2ada-11e9-9574-3a253aeeb884.png)

**Comment by tomasr** [comment]
Thanks, I'll try to reproduce it here.

**Comment by tomasr** [comment]
I have been unable to reproduce this here so far :(

Sorry.

**Comment by giggio** [comment]
Ok, I haven't seen it again. Maybe it was something else. Thanks.
