### ISSUE TITLE
Control Flow Keyword highlighting not working in VS 2019 RC.1

### ISSUE THREAD

**Issue by asser-dk** [tomasr/viasfora#268]
Was testing out VS 2019 and noticed that the control flow keyword highlighting does not appear to be working.

The colours are persisted in Fonts and Colours from what I can tell and the settings are enabled in the Viasfora options section.

Visual Studio Enterprise 2019 Preview
Version 16.0.0.0 Preview 4.1 SVC1

Viasfora
Version 4.2.188

**Comment by tomasr** [comment]
Known issue.

It doesn't work because Visual Studio introduces it's own highlighting of Control Keywords for C# (they are handled by the `Keyword - Control` entry in Fonts and Colors).

**Comment by asser-dk** [comment]
Thanks for the clarification :)

**Comment by tomasr** [comment]
No problem, it's a good question. I'm still trying to decide if I want to "fix it" to go over the VS feature or leave it as is. So feedback would be appreciated :smile:

**Comment by mzhukovs** [comment]
I was just about to file this one as well - it was working in VS2017 and in 2019 I am sure most people will think it broke as well when switching over because all of a sudden it stops! My 2 cents would be to override it since it's exposed as a feature in your [fantastic] extension.
