### ISSUE TITLE
Brace/Parentheses levels never use colors past Level 4

### ISSUE THREAD

**Issue by mzhukovs** [tomasr/viasfora#269]
I see this in both latest VS2017 and VS2019 (ver 16.0 RC 3) - perhaps I am unaware of the logic but I would expect the colors specified in the settings for Levels 1 to 9 would ALL be reflected in the nested parentheses but for some reason it doesn't seem to go past Level 4 before starting over to repeat the colors again. Please let me know if this is intentional (and if so, why)? Thank you in advance.

![image](https://user-images.githubusercontent.com/13161978/54890131-ddaa1f00-4ee2-11e9-938e-a279c037fe2e.png)

![image](https://user-images.githubusercontent.com/13161978/54890118-ce2ad600-4ee2-11e9-9878-0b7389b8fbfa.png)

**Comment by tomasr** [comment]
@mzhukovs You're missing setting the `Rainbow Depth` option which controls how many nested levels are supported. It does default to 4, so that's why you're not seeing the other colors being used.

**Comment by mzhukovs** [comment]
Aha! Figured it was too obvious to be a bug or something. Thanks for the quick response!
