### ISSUE TITLE
Control Flow Keywords - VS2019

### ISSUE THREAD

**Issue by lmorelato** [tomasr/viasfora#271]
I'm trying to change the color for control flow keywords on the new VS2019, but it is not being applied. Maybe I need some additional configuration?

Tks.

![image](https://user-images.githubusercontent.com/12112408/56596527-b5cfd900-65be-11e9-858c-b4c72d4f9d6a.png)

**Comment by tomasr** [comment]
Duplicate of #268.

This is fixed in the [latest dev version](https://ci.appveyor.com/project/tomasr/viasfora/build/artifacts) which I haven't pushed to the marketplace yet.

**Comment by lmorelato** [comment]
Tks!

**Comment by TylerGlaiel** [comment]
appears to still be not working in VS 16.3.4 (installed the latest dev version)

**Comment by Prologh** [comment]
Had the same problem with VS 2019 16.3.7, installed last dev version from @tomasr link and it worked. Thanks!

**Comment by sylveon** [comment]
@tomasr any plans on releasing a new build on the store soon?
