### ISSUE TITLE
Provide ability to treat block and statement scope separately for "rainbow lines"

### ISSUE THREAD

**Issue by marzer** [tomasr/viasfora#272]
Hi,

The "rainbow lines" feature is great for blocks, namespaces etc, but I find that once it gets to a statement-level scope (i.e. horizontal lines) it's actually pretty annoying and distracting. I'd love the option to disable the horizontal part of it altogether, so it only ever shows the innermost 'vertical' scope.

E.g. this:

![image](https://user-images.githubusercontent.com/3958019/57016672-16e15780-6c24-11e9-825e-0b647126e213.png)

displayed as this:

![image](https://user-images.githubusercontent.com/3958019/57016694-324c6280-6c24-11e9-9f10-4ff7c69771c4.png)

Regardless of where in the `Typed` scope I put the cursor.

Alternatively, the ability to do both simultaneously but reduce the line thickness or alpha strength of the horizontal part might also work.

**Comment by tomasr** [comment]
I've added an option called `RainbowLinesMode` to support this. Should be in the next public release.

**Comment by marzer** [comment]
Awesome, thanks @tomasr!
