### ISSUE TITLE
XML outlining broken in 4.2.188

### ISSUE THREAD

**Issue by cdonnellytx** [tomasr/viasfora#279]
So it looks like 4.2.188 may have broken XML outlining (similar to how C# outlining was broken in #143).

I went through my extensions (disabling them all and re-enabling them a few at a time), and narrowed it down to just Viasfora.  I uninstalled/reinstalled it as well, but that also did not fix it.

I looked to see if there was a way to disable it for just XML, but the "Languages" page in Tools > Options is completely blank, and the exported config does not have anything indicating that is possible (I see `Cpp_Enabled`, `CSS_Enabled`, and more, but not one for XML.).

I've attached [my settings][20190821-viasfora.xml] in case it's just something I'm missing.

Thanks!

\# Chris

[20190821-viasfora.xml]

[20190821-viasfora.xml]: https://github.com/tomasr/viasfora/files/3526183/20190821-viasfora.xml.txt

**Comment by tomasr** [comment]
Could I ask what other extensions you're using here? And what's the VS version?

If the tools -> option page is not working for you, I would say you probably have a broken Viasfora installation (which sometimes can happen after upgrades). Could you try uninstalling it and reinstalling it again and see if that fixes it?

Also, the options for controlling XML editor enhancements are all in the Viasfora -> XML Editor side, not under languages.

**Comment by cdonnellytx** [comment]
I'm currently running the following, although I've seen it for a while now (at least a couple of months):

* Visual Studio Enterprise 2019 (16.2.3)
* Visual Studio Enterprise 2017 (15.9.15)

I was able to reproduce the problem by installing Viasfora into a clean [experimental instance of VS2019](https://docs.microsoft.com/en-us/visualstudio/extensibility/the-experimental-instance?view=vs-2019); XML folding is disabled there as well.

I've also ruled out other possibilities like EditorConfig possibly being the culprit (I've tested it on a path that doesn't have one).

Also, it turns out I didn't realize the Viasfora > Languages page is blank because it's just a placeholder -- for some reason I didn't see that the languages are underneath it.  So please disregard that part.

**Comment by tomasr** [comment]
Thanks for testing.

I'm not sure what to tell you, honestly. XML Folding seems to be working just fine for me:

![image](https://user-images.githubusercontent.com/16179/63451743-7ef1be80-c40a-11e9-8a5f-8db15693ad34.png)

Are you sure you don't have the `Enter outlining mode when files open` option under Tools -> Options -> Text Editor -> XML -> Miscellaneous option unchecked?

**Comment by cdonnellytx** [comment]
It's definitely checked in all instances, including the Experimental one.

I also verified disabling global extensions (like Live Share) does _not_ solve the problem.

I _did_ find that it appears none of my files are loading with an outline if I have Viasfora enabled -- including C# and JSON files.  If I use an outlining shortcut (e.g., Ctrl+M, Ctrl+O for "Collapse to Definitions"), it enables outlining and collapses sections as one would expect.  However, none of the outlining shortcuts seem to enable XML.

So there's two things going on when Viasfora is loaded:

1. Automatic outlining isn't being turned on by default (but can be turned on per file)
2. For XML, automatic outlining cannot be turned on (even if I add a hotkey to the action).

Can you think of any reason that outline loading might be deferred with Viasfora?

**Comment by tomasr** [comment]
Just checked your configuration file, and you have this:

```xml
<AutoExpandRegions>Disable</AutoExpandRegions>
```

That's actually disabling outlining on file open, so explains what you're seeing. This is controlled by the `Expand regions on open` setting in Viasfora:

![image](https://user-images.githubusercontent.com/16179/63456186-fb3ccf80-c413-11e9-806a-b7dbe2703e3b.png)

Set this to either `No` or `Expand` and the problem should go away.

**Comment by cdonnellytx** [comment]
Changing that fixed it.

I don't recall changing it, though... is that an old default, or is it intentional for automatic outlining to be off by default?

**Comment by tomasr** [comment]
No, that option has always defaulted to `No`, so you must have changed it at some point in time.
