### ISSUE TITLE
Reseting the text editor zoom always to default

### ISSUE THREAD

**Issue by devbrsa** [tomasr/viasfora#281]
It's reseting the text editor zoom always to 100%

**Comment by tomasr** [comment]
What's the context here? Can you explain a bit better what you're seeing?

**Comment by devbrsa** [comment]
Sure, after installing the extension. Whenever opening a new file using VS, it resets the zoom view to 100%. By default it keeps the latest you left.

**Comment by golavr** [comment]
i'm also having this behavior.
it's a bit annoying since you need to zoom each file you open
