### ISSUE TITLE
Bold as Italics issue

### ISSUE THREAD

**Issue by nurbles** [tomasr/viasfora#282]
I had a problem with the Enable 'Bold as Italics' setting today.  I had been using it for numbers and comments, but I recently found a font I prefer that does not look good in italic, so I wanted to disable the feature.  It was a whole lot more work than it should have been.  Here are the steps I followed:

1.  I set 'Bold as Italics' to False and save/close the configuration tool
2.  Numbers and comments were still rendered in italic instead of bold
3.  I restarted VS2019 (16.3.3)
4.  Numbers and comments were still in italics
5.  Use 'Fonts and Colors' to remove **bold** from **ALL** color settings
6.  Numbers and comments were still in italics
7.  Restart VS2019
8.  Numbers and comments were still in italics
9.  Disable Viasfora
10.  Numbers and comments are no longer in italics (yeah!)
11.  Restart VS2019
12.  Still no italics (yeah!)
13.  Enable Viasfora
14.  Restart VS2019
15.  Still no italics (yeah!) even after multiple VS2019 restarts.

**Comment by tomasr** [comment]
I haven't been able to reproduce this. You do need to reopen windows when changing the state of the Bold as Italics feature, because VS doesn't provide a way to recreate them when it changes, but a restart should get rid of everything if the feature is disabled.....
