### ISSUE TITLE
The new release

### ISSUE THREAD

**Issue by myCrack** [tomasr/viasfora#288]
Viasfora is a good add-in, but some people can't use the last features of it, because the marketplace has the old version. So, i think you must release the new version.

You already did enough for the new release. You added mpl support which would be useful for mpl community. Also, you added [another features](https://github.com/tomasr/viasfora/issues?q=milestone%3Av4.3+is%3Aclosed) which would be useful for the all viasfora users.

I want the new version to be in the marketplace because of mpl community. I think, that the add-ins installation from not the marketplace is somehow harder than installation from the marketplace, especially for new vs users. And mpl community has people with very diverse experiences, so, i can't recommend to them add-in which is not in the marketplace.

As i see, the only problem which prevent the new release is the incomplete x++ support, and i think that you can manage it. You can release viasfora with semi-implemented x++ support. As x++ vs add-in is private, any unimplemented feature will not be a problem for anyone except of small group of people, only which, has the access to the x++ add-in. Or, you can postpone this task. The guy disappeared, and did not contribute to the support anymore.

**Comment by tomasr** [comment]
I've pushed a new version on the marketplace.
