### ISSUE TITLE
Viasfora for Visual Studio for Mac 

### ISSUE THREAD

**Issue by JulesMoorhouse** [tomasr/viasfora#300]
I saw the closed issue 212 saying that the editor is different. However this is no longer the case.

It uses the same editor now 

https://devblogs.microsoft.com/visualstudio/visual-studio-for-mac-top-features-of-the-new-editor/

How’s about an update 😀 ? 

I would be happy to test this for you!

**Comment by tomasr** [comment]
Unfortunately, I don't own a Mac at the moment, so even looking at this for the time being is... not possible :(
