### ISSUE TITLE
Mistakenly coloring escape character in comments

### ISSUE THREAD

**Issue by HO-COOH** [tomasr/viasfora#301]
![bug](https://user-images.githubusercontent.com/42881734/97171018-b79dce00-175a-11eb-819d-9c1a2d7767a0.png)
Maybe consider not coloring escape character in comments? Especially for doxygen comments.

**Comment by tomasr** [comment]
They are not supposed to be. What language is this?

**Comment by HO-COOH** [comment]
@tomasr 
It's a C++ file. This is a comparison for enabling and disabling the setting.
![image](https://user-images.githubusercontent.com/42881734/103180059-dfdba300-4857-11eb-9080-5c01a6d8258c.png)
![image](https://user-images.githubusercontent.com/42881734/103180069-e9fda180-4857-11eb-9f20-e8db0303d219.png)

**Comment by myCrack** [comment]
The same on mpl. I used to think that this was made intentionally.

**Comment by tomasr** [comment]
Should be fixed on the latest development build.
