### ISSUE TITLE
Rainbow brackets oddity with F# Attributes.

### ISSUE THREAD

**Issue by realparadyne** [tomasr/viasfora#302]
Attribute brackets are in different colours.  I think this occurs only after the file is processed by the F# compiler service and full colourisation is applied.

VS Version 16.8.0 Preview 6.0

![image](https://user-images.githubusercontent.com/2536830/98370361-5e734b80-2032-11eb-97e8-925fa63cea74.png)

**Comment by tomasr** [comment]
Are you using a font with ligatures for [< and >]?

Unfortunately, those really mess up things....

**Comment by realparadyne** [comment]
Well that clears it up then.  Yes I do prefer coding fonts with ligatures. It appears to be the only place that looks wrong, presumably because it's the only place a character pair is used for each bracket?
