### ISSUE TITLE
Rainbow Lines Flashing on Keypress

### ISSUE THREAD

**Issue by ryanbuening** [tomasr/viasfora#309]
I'm not sure if this is expected, but when I have Rainbow Lines enabled and I'm typing, the lines flash on each keypress:

![Animation](https://user-images.githubusercontent.com/812974/121252949-96679900-c876-11eb-967f-edde54939dcc.gif)

**Comment by bozonsky** [comment]
Can confirm, this problem seemingly appeared since release of VS2019 ver. 16.10.0.
Very annoying, I got used to perfect performance of Viasfora. :(

**Comment by luisllamasbinaburo** [comment]
Confirmed too

**Comment by tomasr** [comment]
Do you have any other extensions installed? I can't seem to reproduce it yet.

**Comment by ryanbuening** [comment]
I have the following extensions enabled:

- Add New File
- AsyncFixer for Visual Studio 2019
- Cloud Explorer for VS 2019 Preview
- EditorConfig Language Service
- ErrorHelper
- File Icons
- Fix Mixed Tabs
- Format document on Save
- Middle Click Scroll
- Move Type To File - 2017/19
- NuGetRecommender [Preview]
- One Dark Pro
- Output enhancer
- Sharpen
- Solution Error Visualizer
- Viasfora
- Word Highlight With Margin

Anyone else with this issue have any of those extensions installed too?

**Comment by tomasr** [comment]
I wonder if it's related to Issue #301 ...

**Comment by ryanbuening** [comment]
I can let you know when 4.4 is released to see if it's fixed.

**Comment by ValZapod** [comment]
It looks like a bug but I do like in my Visual Studio 2022.

**Comment by ryanbuening** [comment]
@tomasr this appears to be much better than before 👍. I do still notice some occasional flashing (gif below). Not sure if anything further can be done.

![flashing](https://user-images.githubusercontent.com/812974/167639104-0ba018cd-e660-43fa-9d25-5bbbf0868890.gif)

**Comment by ValZapod** [comment]
That is a different bug. The color of the [] has nothing to do with the newly rendered line.

**Comment by ValZapod** [comment]
Gray color is just the color of Visual Studio. It had to first register to work. I do have same bug in VS 2022.
