### ISSUE TITLE
Wrong escape coloring in C++ for raw string literals

### ISSUE THREAD

**Issue by nirlivne** [tomasr/viasfora#311]
```
// Simple string
std::string s1 = "item1\titem2\tnewline\n";

// Raw literal string (escape characters should not have colors)
std::string s2 = R"(item1\titem2\tnewline\n)";
```

**Comment by tomasr** [comment]
I think this is related to issue #301. Should be fixed with the same change.

**Comment by ZaquL** [comment]
Is this correct? 

![изображение](https://user-images.githubusercontent.com/104958042/167321934-aaed073c-b869-4eea-94dc-2df75936ca8a.png)

**Comment by nirlivne** [comment]
No, s2 should have no escape colors
It is a raw string
