### ISSUE TITLE
Excessive memory usage when building with Resharper C++

### ISSUE THREAD

**Issue by samaursa** [tomasr/viasfora#313]
I have an interesting issue where Viasfora can gobble up huge amounts of RAM but only when a Resharper C++ Build and Run is used (i.e. when building through the Resharper Build and Run tool).

I have these screenshots from Jetbrains (since I originally though the issue was with Resharper C++ and sent them a bug about it) that may be helpful. If there's something else I can do to help you pinpoint the issue, let me know.

![viasfora_rainboxprovider_ram_usage](https://user-images.githubusercontent.com/817849/139448616-b92f2a02-a11b-45bc-803b-7ad78d56f3da.PNG)

![viasfora_rainboxprovider_ram_usage_2](https://user-images.githubusercontent.com/817849/139448596-649a0bbd-95b8-44df-8a11-0f57bf1510ef.PNG)
n

**Comment by tomasr** [comment]
Thanks for the report. I don't have access to Resharper, but I'll try to see what I can dig up.
