### ISSUE TITLE
Any plan to make the extension available for VS 2022

### ISSUE THREAD

**Issue by Evangelink** [tomasr/viasfora#314]
Hi,

First of all, thank you for this awesome extension! I am wondering if you are planning on releasing a new version of the extension compatible with VS2022?

**Comment by andresparrab** [comment]
Hi!

Dito that! 
I think many people would be very thanksfukk if this wouls support VS2022.

**Comment by Grahamvs** [comment]
I've been using this extension for a few years now, and it would be really sad if we're not able to continue using it with newer versions of Visual Studio.

Regardless of whether or not you decide to update it, I would like to thank you for sharing it with us :)

**Comment by SanderBreivik** [comment]
👍 This extension has been improving the readability of my code! I would really like it in 2022 as well!

**Comment by SanderBreivik** [comment]
If anyone has time [the tutorial to port is here](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022)

**Comment by Grahamvs** [comment]
I've had a quick look at porting it and I managed to get some of it working (mainly the coloured text), but the options don't load.

@tomasr if you're interested, I had to upgrade all project runtimes to v4.7.2, convert the NuGet packages to Package References and replace all the existing NuGet packages with "Microsoft.VisualStudio.Sdk" v17. This, unfortunately, means it's not compatible with VS 2019 and older.

It is possible to split it so you can support all versions, but it doesn't seem like an easy task (a few other extension devs have resorted to releasing 2 separate extensions).

I found a call to load "Microsoft.VisualStudio.Shell.10.", however, it seems it's still trying to reference it somewhere else that I can't find...

I will continue to look into this in my spare time, but I have very little of that at the moment. Hopefully this helps someone else

**Comment by andresparrab** [comment]
Hi Grahamvs, 
that is awsome, Even if it mean that it will not be compatible with vs 2019 and older. Because im going to exclusive run vs 2022.
But  I trying to understand what you wrote to se if i can understand step by step.
1. Download Viasfora from git
2. Upgrade all project runtimes to v4.7.2
3. Convert the Nuget PAckages to Package Reference ?? this part did not cumpute in my brain :) 

Im trying to read how to do it but is not as easy i think, or i missing something

**Comment by Odiriuss** [comment]
@andresparrab check out this article for Package References https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference

**Comment by YataoWang** [comment]
Hello,

Thanks for this useful extension.  Does it have a plan to support the VS2022?

**Comment by fihorvat** [comment]
Thanks @tomasr for great extension.
Until this extension gets updated to new version so that it supports VS2022 you can take the release from the fork of this repository [here](https://github.com/IllyaTheHath/viasfora) thanks to @IllyaTheHath
Just download the `Viasfora.vsix` and run it.
I tried and it works great.

**Comment by dmaidon** [comment]
Support for VS2022 would be a big plus.

**Comment by andresparrab** [comment]
@fihorvat you are a life saver. I have really tried to follow @Grahamvs and @Odiriuss  help to port this to vs 2022 but I guess I'm not that smart to to that. and also cant spend to much work time on this. now i downloaded the  Viasfora from @IIIyaTheHath and I can see again :)

**Comment by tomasr** [comment]
Thanks all. It's a work in progress. It's going to take me a few days to get it done, as I don't want to completely leave existing users on previous Visual Studio versions out in the cold.

**Comment by lando786** [comment]
Awesome news, thanks for this!

**Comment by CoreDumpSoftware** [comment]
Giving more details to @fihorvat's comment.

Cloned the repo he linked
Installed .Net 4.7.2. SDK
Opened the project, let VS2022 upgrade all the projects for me. It wanted to do it as 4.8 but for some reason did all but one as 4.7.2. The version worked just fine but had to manually set the Viasfora.Settings project as 4.7.2.
Compiled Viasfora
Ran the .visx file from the Bin/Debug folder after compilation.  VS2022 is now colorful again!

**Comment by jerviscui** [comment]
Loved this extension!

**Comment by mzy666888** [comment]
Loved this extension!

**Comment by gliddie** [comment]
Hello Tomasr,

do you have any news for us?

I would love to have your extension in VS2022

Thank you,

**Comment by aengusjiang** [comment]
Waiting for vs2022 version

**Comment by WhiskeyJack65** [comment]
Want to say thanks for viasfora, such a great VS extension.  Sure hope you manage to find the time to get it working for VS 2022.

**Comment by TanvirArjel** [comment]
It seems like support for VS2022 would not be available in 2022!

**Comment by ValZapod** [comment]
> It seems like support for VS2022 would not be available in 2022!

Meanwhile it works for me, LOL.

**Comment by stefan-tb** [comment]
Same here. Viasfora is one of the reasons why I am still on VS2019. ;) I would love to see an updated version for VS2022, highly appreciated! Kudos.

**Comment by jeoffman** [comment]
[This fork](https://github.com/jeoffman/viasfora ) should compile in VS2022 and you can install the generated .vsix :
The code changes are minor - just some namespace fixes in "using". Everything else is updating the sln and csproj nugets and packageref stuff.
I disabled the unit tests - I'm not interested in porting all the old VS2017 shims or supporting EOL VS versions.

**Comment by SSyyll0929** [comment]
👍 This extension has been improving the readability of my code! I would really like it in 2022 as well!

**Comment by stefan-tb** [comment]
Seems like tomasr own 2022 branch is good enough, compiling and working. At least the colored brackets (the most important feature for me, didnt test all the other options). Thanks!

**Comment by GambaJo** [comment]
I hope the branch is stable soon.

**Comment by tomasr** [comment]
The develop branch is now vs2022 only. Still need to work through a few things before I can publish.

**Comment by tomasr** [comment]
done now.
