### ISSUE TITLE
xml prefix/closing tags not working with web form editor?

### ISSUE THREAD

**Issue by nwein4288** [tomasr/viasfora#317]
For 2019, Viasfora applied the prefix/ closing coloration for the web form editor
2019:
![image](https://user-images.githubusercontent.com/84468294/167624944-a90bc5b8-771a-4c80-844c-efdd061f1f15.png)

in 2022, it does not appear to apply the coloration to the web form editor anymore. XML editor works as intended, though.
2022:
![image](https://user-images.githubusercontent.com/84468294/167625173-7d4d8702-381c-4598-a773-db37b9f6ed9a.png)

Was wondering if there is a way to apply them to the web form editor like 2019?

**Comment by WilliamITS** [comment]
This would also be greatly appreciated for razor pages.

**Comment by tomasr** [comment]
I think I might have managed to fix the WebForms editor for vs2022. Still looking at the razor pages one.
