### ISSUE TITLE
Can't install on VS2019 and earlier

### ISSUE THREAD

**Issue by nnorm** [tomasr/viasfora#319]
It seems the manifest in the VSIX package (_downloaded from the repository's release page_) indicates to the VSIX Installer that the extension is **not compatible with versions earlier than 17.0**. I've had trouble installing it from Microsoft's extension marketplace as well.
Is that the intended behavior? (_following compatibility-with-VS2022 update_)

**Comment by tomasr** [comment]
This is expected. See my reply to #316 .
