### ISSUE TITLE
C++ Format Specifiers not showing up perfectly

### ISSUE THREAD

**Issue by Pcres91** [tomasr/viasfora#320]
two-letter format specifiers seem to not come out nicely.
```
printf("Read failed 0x%lx (%lu)", address, size);
```

This should highlight `lx` and `lu` as part of the format specifier, but only the `l` is in both cases. The same happens for 3-letter specifiers too - only the first letter is highlighted.

**Comment by tomasr** [comment]
Thanks for the reports. I've made a few changes to try to improve this handling.
