### ISSUE TITLE
Please, re-enable installing newest Viasfora release with improvements and fixes for Visual Studio 2019

### ISSUE THREAD

**Issue by Twoleeland** [tomasr/viasfora#322]
Hello,

is there a severe reason why you dropped installing the newest release of Viasfora to Visual Studio 2019?

I would be pleased if you would reintroduce the installation of Viasfora for Visual Studio 2019.

Best regards

**Comment by Laicure** [comment]
This is so sad, where is Viasfora for 2019?
At least, leave a working version for 2019 :(

**Comment by tomasr** [comment]
As per the readme, last version supporting VS2019 can be found here: https://github.com/tomasr/viasfora/releases/tag/v4.3

**Comment by rj-rl** [comment]
Thank you for the link! There doesn't appear to be find any info about previous versions support in the readme though.

**Comment by tomasr** [comment]
Sorry about that, I thought I had updated the readme, but guessed I only updated the marketplace page. I have updated it now.

**Comment by Laicure** [comment]
Where is your readme update? It is still for "Visual Studio 2020"

I pulled a commit for your readme but you just closed it. 😒
