### ISSUE TITLE
Rainbow lines appear on top of 'peek definition' areas.

### ISSUE THREAD

**Issue by realparadyne** [tomasr/viasfora#325]
Using Peek Definition when rainbow lines are displayed seems to have the wrong ordering of layers, so the line cuts through the definition code.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/2536830/176507612-e2db2312-395d-47b2-be6b-67434c2031fd.png">

**Comment by tomasr** [comment]
Thanks for the report. Seems like changing the layer the Rainbow Lines are rendered in fixes the issue.
