### ISSUE TITLE
[Request] Ability to Enable/Disable Plugin features

### ISSUE THREAD

**Issue by k-saenz** [tomasr/viasfora#327]
There are some features that are unique to this plugin. It would be great to be able to only use certain parts of it (i.e. just rainbow braces).

**Comment by tomasr** [comment]
You can already enable/disable most features individually from Tools -> Options -> Viasfora. Is this not enough?

**Comment by k-saenz** [comment]
You are absolutely right, thank you! Probably a good idea to mention it in the docs somewhere.
