### ISSUE TITLE
C# 11 Raw String Literals break coloring

### ISSUE THREAD

**Issue by Tim-Pohlmann** [tomasr/viasfora#339]
![image](https://user-images.githubusercontent.com/20153123/227893712-19fd9ad2-5b07-453d-a739-6d1056d5d86a.png)
It doesn't detect the closing parenthesis, which also has an effect on brackets following later.

**Comment by tomasr** [comment]
Made some initial changes to support this. Not enough probably.

**Comment by Tim-Pohlmann** [comment]
This is still an issue in 4.5.220
There are also some issues with curly brackets inside a raw string.
