### ISSUE TITLE
Usage of deprecated IQuickInfoBroker causes VS hangs

### ISSUE THREAD

**Issue by olegtk** [tomasr/viasfora#342]
Visual Studio telemetry indicates Viasfora's usage of deprecated IQuickInfoBroker is causing hangs. The solution is to migrate to IAsyncQuickInfoBroker and I'm willing to contribute the fix. Would you be OK to release an update, @tomasr? Thanks!

**Comment by tomasr** [comment]
I have made here some changes, but I had to completely disable `RainbowToolTipPresenter` as it doesn't seem like `IAsyncQuickInfoSession` supports the same functionality as `IQuickInfoSession` for me to continue supporting this. I am not sure it was ever strictly required (or it might have been trying to fix some cosmetic issues in VS, can't remember anymore). Hopefully doesn't hurt anything...

**Comment by olegtk** [comment]
Thanks, @tomasr!
