### ISSUE TITLE
Coloring breaks after using interpolation

### ISSUE THREAD

**Issue by Telchark** [tomasr/viasfora#344]
I had line like this 
` sql.Append($"    SELECT " + string.Join(", ", stsRti.KnownColumnNames.Select(c => $"TBL.{c}")) + ", ORA_ROWSCN, MEMO.MEMO OPIS_MEMO, ROW_NUMBER() OVER (ORDER BY TBL.FAKTURA, TBL.RECNO) RN__\n");`
and after I changed it to this:
`sql.Append($"    SELECT { string.Join(", ", stsRti.KnownColumnNames.Select(c => $"TBL.{c}"))}, ORA_ROWSCN, MEMO.MEMO OPIS_MEMO, ROW_NUMBER() OVER (ORDER BY TBL.FAKTURA, TBL.RECNO) RN__\n");`
the coloring of last bracket(right before `;`) is not occuring and the rest of the document thinks it's inside bracket right after `Append`
Example:
Before:
![before](https://github.com/tomasr/viasfora/assets/56097001/47f556b2-04b4-4ad9-b3bc-aa64cc0ec009)
After:
![after](https://github.com/tomasr/viasfora/assets/56097001/232537df-6ab8-4e1e-ae5f-4128245aeeac)

**Comment by 1CDE683405CAC00EAD7242DCD02BC0AB** [comment]
I have the similar question, but when I use raw string with interpolation in .Net8.
Now, I disable the C# coloring and use brace-coloring comes with VS.
Waiting for repair~~~

**Comment by mayka-mack** [comment]
I can confirm the same issue when using string interpolation with a custom class that allows adding color to specific words in the console.

![image](https://github.com/tomasr/viasfora/assets/110175832/5e5228cf-a72d-4c97-b2ca-7b616e5e5679)

**Comment by tomasr** [comment]
I've made a few improvements here that hopefully sorts some of these issues.
