### ISSUE TITLE
VS 2015 Preview Fonts & Colors

### ISSUE THREAD

**Issue by rog1039** [tomasr/viasfora#98]
Hi,

Just wanted to report that the Viasfora colors do not show up in the Fonts & Colors dialog box in the VS 2015 preview on my machine.  Other than that, the extension works great.

Resharper had the same issue until they released an update, so perhaps VS 2015 changed the way extensions registered into the Fonts & Colors dialog box?

Love the extension, rainbow colors on brackets/braces/parens is awesome!

Thanks,
Paul

**Comment by Trass3r** [comment]
Thanks a lot this actually helped.
Not even ClearAllCaches in the Initialize method was enough, had to add this refresh code.
